export interface ModelPresetTemplate {
  id: string;
  name: string;
  provider: string;
  modelName: string;
  displayName: string;
  modelFamily: string;
  parameterCount: string;
  architecture: string;
  quantization: string;
  localOrCloud: 'cloud' | 'local';
  contextWindow: string;
  isReasoningModel: boolean;
  notes: string;
  // Artificial Analysis benchmark data
  aaIntelligenceIndex?: number;
  aaModelId?: string;
  aaEvaluations?: {
    gpqa?: number;
    math?: number;
    coding?: number;
    throughputTokSec?: number;
    priceInputPer1M?: number;
    priceOutputPer1M?: number;
  };
}

export const PROVIDER_CATEGORIES = [
  {
    category: 'Frontier Cloud Labs',
    providers: [
      'Anthropic',
      'OpenAI',
      'Google',
      'DeepSeek',
      'xAI',
      'Meta',
      'Mistral AI',
      'Cohere',
      'Alibaba',
      'Amazon Bedrock',
      'Microsoft',
    ],
  },
  {
    category: 'Local Inference Engines',
    providers: [
      'Ollama',
      'LM Studio',
      'vLLM',
      'SGLang',
      'LocalAI',
      'llama.cpp',
      'Jan',
      'ExLlamaV2',
      'Local / Self-Hosted',
    ],
  },
  {
    category: 'Cloud Gateways & Aggregators',
    providers: [
      'OpenRouter',
      'Together AI',
      'Groq',
      'Fireworks AI',
      'Cerebras',
      'DeepInfra',
      'Hugging Face',
      'Perplexity',
      'Novita AI',
    ],
  },
];

export const ALL_COMMON_PROVIDERS = PROVIDER_CATEGORIES.flatMap((c) => c.providers);

export const ARCHITECTURE_PRESETS = [
  { label: 'Transformer (Decoder-only Dense)', desc: 'Standard autoregressive dense transformer architecture' },
  { label: 'Mixture of Experts (MoE)', desc: 'Sparse gated mixture of experts (e.g. Mixtral, Qwen Max, DBRX)' },
  { label: 'Transformer + Multi-Head Latent Attention (MLA)', desc: 'DeepSeek V2/V3 low-memory KV cache architecture' },
  { label: 'Reasoning / Thinking Model', desc: 'Chain-of-thought specialized model (o1, o3, R1, QwQ)' },
  { label: 'Hybrid SSM-Transformer (Mamba / Jamba)', desc: 'State-space model fused with attention layers' },
  { label: 'State Space / Linear RNN (RWKV)', desc: 'Non-transformer linear attention / recurrent architecture' },
  { label: 'Vision-Language Multimodal (VLM)', desc: 'Joint vision and language encoder-decoder' },
  { label: 'Diffusion / Diffusion-Transformer', desc: 'Continuous diffusion based generation model' },
];

export const QUANTIZATION_CATEGORIES = [
  {
    category: 'Full & Native Precision',
    options: [
      { label: 'None / Cloud Native', desc: 'Unquantized default provider cloud deployment' },
      { label: 'BF16 (Bfloat16)', desc: '16-bit Brain floating point standard' },
      { label: 'FP16 (Half Precision)', desc: 'Standard 16-bit floating point' },
      { label: 'FP32 (Single Precision)', desc: 'Full 32-bit floating point weights' },
    ],
  },
  {
    category: 'Modern FP8 & Low-Bit Float',
    options: [
      { label: 'FP8 (E4M3)', desc: '8-bit float optimized for inference (Hopper/Ada)' },
      { label: 'FP8 (E5M2)', desc: '8-bit float with wider dynamic range' },
      { label: 'NVFP4 (NVIDIA 4-bit)', desc: 'Next-gen Blackwell 4-bit floating point' },
    ],
  },
  {
    category: 'GGUF / llama.cpp (Local)',
    options: [
      { label: 'Q4_K_M (Recommended 4-bit)', desc: 'Optimal balance of speed, RAM and perplexity' },
      { label: 'Q4_K_S (Fast 4-bit)', desc: 'Slightly smaller 4-bit quantization' },
      { label: 'Q5_K_M (High Quality 5-bit)', desc: 'Near FP16 quality with 5-bit compression' },
      { label: 'Q6_K (6-bit)', desc: 'Highest fidelity local quantization' },
      { label: 'Q8_0 (8-bit Integer)', desc: 'Virtually lossless 8-bit integer quantization' },
      { label: 'Q3_K_M (Compact 3-bit)', desc: 'Aggressive compression for limited VRAM' },
      { label: 'Q2_K (Extreme 2-bit)', desc: 'Ultra-compressed experimental quantization' },
    ],
  },
  {
    category: 'AWQ, EXL2 & GPTQ',
    options: [
      { label: 'AWQ 4-bit', desc: 'Activation-aware weight quantization (vLLM / SGLang)' },
      { label: 'GPTQ 4-bit', desc: 'Second-order error compensation quantization' },
      { label: 'EXL2 4.0 bpw', desc: 'ExLlamaV2 high-throughput 4.0 bits-per-weight' },
      { label: 'EXL2 6.0 bpw', desc: 'ExLlamaV2 high-fidelity 6.0 bits-per-weight' },
      { label: 'HQQ 4-bit', desc: 'Half-Quadratic Quantization' },
    ],
  },
];

export const PARAMETER_SCALE_PILLS = [
  '1.5B',
  '3B',
  '7B',
  '8B',
  '14B',
  '27B',
  '32B',
  '70B',
  'MoE 8x7B',
  'MoE 8x22B',
  'MoE 671B (37B active)',
  '120B+',
  'Proprietary Cloud',
];

export const CONTEXT_WINDOW_PILLS = [
  '8k',
  '16k',
  '32k',
  '64k',
  '128k',
  '200k',
  '1M',
  '2M',
];

export const MODEL_TEMPLATES: ModelPresetTemplate[] = [
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1 (Reasoning / MoE)',
    provider: 'DeepSeek',
    modelName: 'deepseek-reasoner',
    displayName: 'DeepSeek R1',
    modelFamily: 'DeepSeek R1',
    parameterCount: 'MoE 671B (37B active)',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: true,
    notes: 'Reinforcement-learning trained open reasoning model with chain-of-thought verification.',
    aaIntelligenceIndex: 88.6,
    aaModelId: 'deepseek-r1',
    aaEvaluations: {
      gpqa: 71.5,
      math: 97.3,
      coding: 89.2,
      throughputTokSec: 28.5,
      priceInputPer1M: 0.55,
      priceOutputPer1M: 2.19,
    },
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3 (MoE MLA)',
    provider: 'DeepSeek',
    modelName: 'deepseek-chat',
    displayName: 'DeepSeek V3',
    modelFamily: 'DeepSeek V3',
    parameterCount: 'MoE 671B (37B active)',
    architecture: 'Transformer + Multi-Head Latent Attention (MLA)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    notes: 'Ultra-fast sparse MoE architecture with Multi-Head Latent Attention.',
    aaIntelligenceIndex: 78.4,
    aaModelId: 'deepseek-v3',
    aaEvaluations: {
      gpqa: 59.1,
      math: 89.3,
      coding: 84.1,
      throughputTokSec: 62.0,
      priceInputPer1M: 0.27,
      priceOutputPer1M: 1.10,
    },
  },
  {
    id: 'claude-3-7-sonnet',
    name: 'Claude 3.7 Sonnet (Hybrid Thinking)',
    provider: 'Anthropic',
    modelName: 'claude-3-7-sonnet-20250219',
    displayName: 'Claude 3.7 Sonnet',
    modelFamily: 'Claude 3.7',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: true,
    notes: 'Hybrid reasoning and standard generation model with state-of-the-art frontend code synthesis.',
    aaIntelligenceIndex: 91.2,
    aaModelId: 'claude-3-7-sonnet',
    aaEvaluations: {
      gpqa: 75.8,
      math: 96.2,
      coding: 94.0,
      throughputTokSec: 68.0,
      priceInputPer1M: 3.0,
      priceOutputPer1M: 15.0,
    },
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet (Latest)',
    provider: 'Anthropic',
    modelName: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet',
    modelFamily: 'Claude 3.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: false,
    notes: 'Industry benchmark leader for interactive frontend code generation, Canvas, and 3D WebGL.',
    aaIntelligenceIndex: 82.3,
    aaModelId: 'claude-3-5-sonnet',
    aaEvaluations: {
      gpqa: 65.0,
      math: 78.3,
      coding: 92.0,
      throughputTokSec: 74.0,
      priceInputPer1M: 3.0,
      priceOutputPer1M: 15.0,
    },
  },
  {
    id: 'claude-3-5-haiku',
    name: 'Claude 3.5 Haiku',
    provider: 'Anthropic',
    modelName: 'claude-3-5-haiku-20241022',
    displayName: 'Claude 3.5 Haiku',
    modelFamily: 'Claude 3.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: false,
    notes: 'High-speed compact model with strong coding capabilities.',
    aaIntelligenceIndex: 68.9,
    aaModelId: 'claude-3-5-haiku',
    aaEvaluations: {
      gpqa: 54.0,
      math: 69.2,
      coding: 78.5,
      throughputTokSec: 112.0,
      priceInputPer1M: 0.8,
      priceOutputPer1M: 4.0,
    },
  },
  {
    id: 'gpt-4o',
    name: 'OpenAI GPT-4o (Omni)',
    provider: 'OpenAI',
    modelName: 'gpt-4o',
    displayName: 'OpenAI GPT-4o',
    modelFamily: 'GPT-4o',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    notes: 'Flagship multimodal generative model for complex interactive applications.',
    aaIntelligenceIndex: 81.0,
    aaModelId: 'gpt-4o',
    aaEvaluations: {
      gpqa: 53.6,
      math: 76.6,
      coding: 88.0,
      throughputTokSec: 85.0,
      priceInputPer1M: 2.5,
      priceOutputPer1M: 10.0,
    },
  },
  {
    id: 'gpt-4o-mini',
    name: 'OpenAI GPT-4o mini',
    provider: 'OpenAI',
    modelName: 'gpt-4o-mini',
    displayName: 'OpenAI GPT-4o mini',
    modelFamily: 'GPT-4o',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    notes: 'Fast, cost-efficient model for rapid prototyping and component benchmarks.',
    aaIntelligenceIndex: 64.5,
    aaModelId: 'gpt-4o-mini',
    aaEvaluations: {
      gpqa: 40.2,
      math: 70.2,
      coding: 72.0,
      throughputTokSec: 130.0,
      priceInputPer1M: 0.15,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'openai-o3-mini',
    name: 'OpenAI o3-mini (Reasoning)',
    provider: 'OpenAI',
    modelName: 'o3-mini',
    displayName: 'OpenAI o3-mini',
    modelFamily: 'OpenAI o3',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: true,
    notes: 'High-speed reasoning model specialized in STEM, math, and complex code generation.',
    aaIntelligenceIndex: 86.4,
    aaModelId: 'o3-mini',
    aaEvaluations: {
      gpqa: 79.7,
      math: 97.9,
      coding: 92.4,
      throughputTokSec: 95.0,
      priceInputPer1M: 1.1,
      priceOutputPer1M: 4.4,
    },
  },
  {
    id: 'openai-o1',
    name: 'OpenAI o1',
    provider: 'OpenAI',
    modelName: 'o1',
    displayName: 'OpenAI o1',
    modelFamily: 'OpenAI o1',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: true,
    notes: 'Full-scale reasoning model for deep algorithmic and constraint solving.',
    aaIntelligenceIndex: 87.1,
    aaModelId: 'o1',
    aaEvaluations: {
      gpqa: 78.0,
      math: 96.4,
      coding: 91.0,
      throughputTokSec: 45.0,
      priceInputPer1M: 15.0,
      priceOutputPer1M: 60.0,
    },
  },
  {
    id: 'qwen-2-5-coder-32b',
    name: 'Qwen 2.5 Coder 32B (Open Weights)',
    provider: 'Alibaba',
    modelName: 'qwen2.5-coder:32b',
    displayName: 'Qwen 2.5 Coder 32B',
    modelFamily: 'Qwen 2.5',
    parameterCount: '32B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    notes: 'Top-tier open code model matching GPT-4o level code generation in local inference.',
    aaIntelligenceIndex: 74.2,
    aaModelId: 'qwen-2-5-coder-32b-instruct',
    aaEvaluations: {
      gpqa: 48.0,
      math: 82.0,
      coding: 86.5,
      throughputTokSec: 42.0,
      priceInputPer1M: 0.2,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'qwen-2-5-72b',
    name: 'Qwen 2.5 72B Instruct',
    provider: 'Alibaba',
    modelName: 'qwen2.5:72b',
    displayName: 'Qwen 2.5 72B',
    modelFamily: 'Qwen 2.5',
    parameterCount: '70B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    notes: 'Large open-weights flagship model with strong general coding and multilingual mastery.',
    aaIntelligenceIndex: 77.0,
    aaModelId: 'qwen-2-5-72b-instruct',
    aaEvaluations: {
      gpqa: 55.4,
      math: 85.2,
      coding: 85.0,
      throughputTokSec: 25.0,
      priceInputPer1M: 0.4,
      priceOutputPer1M: 1.2,
    },
  },
  {
    id: 'llama-3-3-70b',
    name: 'Meta Llama 3.3 70B Instruct',
    provider: 'Meta',
    modelName: 'llama3.3:70b',
    displayName: 'Llama 3.3 70B',
    modelFamily: 'Llama 3.3',
    parameterCount: '70B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    notes: 'State-of-the-art open weights dense model by Meta AI.',
    aaIntelligenceIndex: 76.5,
    aaModelId: 'llama-3-3-70b-instruct',
    aaEvaluations: {
      gpqa: 54.0,
      math: 81.0,
      coding: 83.2,
      throughputTokSec: 32.0,
      priceInputPer1M: 0.35,
      priceOutputPer1M: 1.0,
    },
  },
  {
    id: 'llama-3-1-8b',
    name: 'Meta Llama 3.1 8B Instruct',
    provider: 'Meta',
    modelName: 'llama3.1:8b',
    displayName: 'Llama 3.1 8B',
    modelFamily: 'Llama 3.1',
    parameterCount: '8B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    notes: 'Fast lightweight local model suitable for rapid HTML testing on consumer laptops.',
    aaIntelligenceIndex: 56.2,
    aaModelId: 'llama-3-1-8b-instruct',
    aaEvaluations: {
      gpqa: 32.8,
      math: 52.0,
      coding: 65.0,
      throughputTokSec: 95.0,
      priceInputPer1M: 0.05,
      priceOutputPer1M: 0.15,
    },
  },
  {
    id: 'gemini-2-0-flash',
    name: 'Google Gemini 2.0 Flash',
    provider: 'Google',
    modelName: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash',
    modelFamily: 'Gemini 2.0',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: false,
    notes: 'Next-generation ultra-fast multimodal model with 1M token context window.',
    aaIntelligenceIndex: 78.9,
    aaModelId: 'gemini-2-0-flash',
    aaEvaluations: {
      gpqa: 62.1,
      math: 84.0,
      coding: 82.5,
      throughputTokSec: 150.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.4,
    },
  },
  {
    id: 'mistral-large-2',
    name: 'Mistral Large 2 (2407)',
    provider: 'Mistral AI',
    modelName: 'mistral-large-latest',
    displayName: 'Mistral Large 2',
    modelFamily: 'Mistral Large',
    parameterCount: '120B+',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    notes: 'Flagship multilingual coding model by Mistral AI with 123B parameters.',
    aaIntelligenceIndex: 77.8,
    aaModelId: 'mistral-large-2407',
    aaEvaluations: {
      gpqa: 54.5,
      math: 76.0,
      coding: 84.0,
      throughputTokSec: 55.0,
      priceInputPer1M: 2.0,
      priceOutputPer1M: 6.0,
    },
  },
  {
    id: 'codestral-2501',
    name: 'Mistral Codestral 2501',
    provider: 'Mistral AI',
    modelName: 'codestral-latest',
    displayName: 'Codestral 25.01',
    modelFamily: 'Codestral',
    parameterCount: '22B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '256k',
    isReasoningModel: false,
    notes: 'Specialized code generation and FIM (Fill-in-the-Middle) model by Mistral AI.',
    aaIntelligenceIndex: 72.0,
    aaModelId: 'codestral-2501',
    aaEvaluations: {
      gpqa: 46.2,
      math: 70.0,
      coding: 87.0,
      throughputTokSec: 90.0,
      priceInputPer1M: 0.3,
      priceOutputPer1M: 0.9,
    },
  },
  {
    id: 'phi-4',
    name: 'Microsoft Phi-4 (14B)',
    provider: 'Microsoft',
    modelName: 'phi4:14b',
    displayName: 'Microsoft Phi-4',
    modelFamily: 'Phi-4',
    parameterCount: '14B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '16k',
    isReasoningModel: false,
    notes: 'Compact synthetic-data trained reasoning and code model with exceptional benchmark density.',
    aaIntelligenceIndex: 71.5,
    aaModelId: 'phi-4',
    aaEvaluations: {
      gpqa: 51.0,
      math: 80.4,
      coding: 80.0,
      throughputTokSec: 65.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.3,
    },
  },
];
