export interface ModelPresetTemplate {
  id: string;
  name: string;
  provider: string;
  modelName: string;
  displayName: string;
  modelFamily: string;
  parameterCount: string;
  architecture: string;
  quantization: string;
  localOrCloud: 'cloud' | 'local';
  contextWindow: string;
  isReasoningModel: boolean;
  notes: string;
  categoryTag?: string;
  // Artificial Analysis benchmark data
  aaIntelligenceIndex?: number;
  aaModelId?: string;
  aaEvaluations?: {
    gpqa?: number;
    math?: number;
    coding?: number;
    throughputTokSec?: number;
    priceInputPer1M?: number;
    priceOutputPer1M?: number;
  };
}

export const PROVIDER_CATEGORIES = [
  {
    category: 'Frontier Cloud Labs',
    providers: [
      'Anthropic',
      'OpenAI',
      'Google',
      'DeepSeek',
      'xAI',
      'Meta',
      'Mistral AI',
      'Moonshot AI (Kimi)',
      'MiniMax',
      '01.AI (Yi)',
      'Cohere',
      'Alibaba',
      'Amazon Bedrock',
      'Microsoft',
    ],
  },
  {
    category: 'Local Inference Engines',
    providers: [
      'Ollama',
      'LM Studio',
      'vLLM',
      'SGLang',
      'LocalAI',
      'llama.cpp',
      'Jan',
      'ExLlamaV2',
      'Local / Self-Hosted',
    ],
  },
  {
    category: 'Cloud Gateways & Aggregators',
    providers: [
      'OpenRouter',
      'Together AI',
      'Groq',
      'Fireworks AI',
      'Cerebras',
      'DeepInfra',
      'Hugging Face',
      'Perplexity',
      'Novita AI',
    ],
  },
];

export const ALL_COMMON_PROVIDERS = PROVIDER_CATEGORIES.flatMap((c) => c.providers);

export const ARCHITECTURE_PRESETS = [
  { label: 'Transformer (Decoder-only Dense)', desc: 'Standard autoregressive dense transformer architecture' },
  { label: 'Mixture of Experts (MoE)', desc: 'Sparse gated mixture of experts (e.g. Mixtral, Qwen Max, DBRX)' },
  { label: 'Transformer + Multi-Head Latent Attention (MLA)', desc: 'DeepSeek V3/V4 low-memory KV cache architecture' },
  { label: 'Reasoning / Thinking Model', desc: 'Chain-of-thought specialized model (Opus 5, GPT-5.6 Sol, V4 Pro)' },
  { label: 'Hybrid SSM-Transformer (Mamba / Jamba)', desc: 'State-space model fused with attention layers' },
  { label: 'State Space / Linear RNN (RWKV)', desc: 'Non-transformer linear attention / recurrent architecture' },
  { label: 'Vision-Language Multimodal (VLM)', desc: 'Joint vision and language encoder-decoder' },
  { label: 'Diffusion / Diffusion-Transformer', desc: 'Continuous diffusion based generation model' },
];

export const QUANTIZATION_CATEGORIES = [
  {
    category: 'Full & Native Precision',
    options: [
      { label: 'None / Cloud Native', desc: 'Unquantized default provider cloud deployment' },
      { label: 'BF16 (Bfloat16)', desc: '16-bit Brain floating point standard' },
      { label: 'FP16 (Half Precision)', desc: 'Standard 16-bit floating point' },
      { label: 'FP32 (Single Precision)', desc: 'Full 32-bit floating point weights' },
    ],
  },
  {
    category: 'Modern FP8 & Low-Bit Float',
    options: [
      { label: 'FP8 (E4M3)', desc: '8-bit float optimized for inference (Hopper/Blackwell)' },
      { label: 'FP8 (E5M2)', desc: '8-bit float with wider dynamic range' },
      { label: 'NVFP4 (NVIDIA 4-bit)', desc: 'Next-gen Blackwell 4-bit floating point' },
    ],
  },
  {
    category: 'GGUF / llama.cpp (Local)',
    options: [
      { label: 'Q4_K_M (Recommended 4-bit)', desc: 'Optimal balance of speed, RAM and perplexity' },
      { label: 'Q4_K_S (Fast 4-bit)', desc: 'Slightly smaller 4-bit quantization' },
      { label: 'Q5_K_M (High Quality 5-bit)', desc: 'Near FP16 quality with 5-bit compression' },
      { label: 'Q6_K (6-bit)', desc: 'Highest fidelity local quantization' },
      { label: 'Q8_0 (8-bit Integer)', desc: 'Virtually lossless 8-bit integer quantization' },
      { label: 'Q3_K_M (Compact 3-bit)', desc: 'Aggressive compression for limited VRAM' },
      { label: 'Q2_K (Extreme 2-bit)', desc: 'Ultra-compressed experimental quantization' },
    ],
  },
  {
    category: 'AWQ, EXL2 & GPTQ',
    options: [
      { label: 'AWQ 4-bit', desc: 'Activation-aware weight quantization (vLLM / SGLang)' },
      { label: 'GPTQ 4-bit', desc: 'Second-order error compensation quantization' },
      { label: 'EXL2 4.0 bpw', desc: 'ExLlamaV2 high-throughput 4.0 bits-per-weight' },
      { label: 'EXL2 6.0 bpw', desc: 'ExLlamaV2 high-fidelity 6.0 bits-per-weight' },
      { label: 'HQQ 4-bit', desc: 'Half-Quadratic Quantization' },
    ],
  },
];

export const PARAMETER_SCALE_PILLS = [
  '1.5B',
  '3B',
  '7B',
  '8B',
  '14B',
  '27B',
  '32B',
  '70B',
  'MoE 8x7B',
  'MoE 675B (41B active)',
  'MoE 1.6T (49B active)',
  '2.4T MoE',
  '2.8T MoE',
  'Proprietary Cloud',
];

export const CONTEXT_WINDOW_PILLS = [
  '32k',
  '64k',
  '128k',
  '200k',
  '500k',
  '1M',
  '2M',
  '4M',
];

export const MODEL_TEMPLATES: ModelPresetTemplate[] = [
  // ==========================================
  // ⚡ ANTHROPIC CLAUDE 5 GENERATION (2026)
  // ==========================================
  {
    id: 'claude-opus-5',
    name: '👑 Claude Opus 5 (Reasoning & Agentic)',
    provider: 'Anthropic',
    modelName: 'claude-opus-5-202607',
    displayName: 'Claude Opus 5',
    modelFamily: 'Claude 5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'Anthropic Claude 5 (2026)',
    notes: 'Anthropic flagship (July 24, 2026) featuring deep extended thinking, agentic workflows, and 1M context.',
    aaIntelligenceIndex: 96.4,
    aaModelId: 'claude-opus-5',
    aaEvaluations: {
      gpqa: 84.5,
      math: 98.8,
      coding: 97.2,
      throughputTokSec: 62.0,
      priceInputPer1M: 5.0,
      priceOutputPer1M: 25.0,
    },
  },
  {
    id: 'claude-sonnet-5',
    name: '⚡ Claude Sonnet 5 (Daily Driver)',
    provider: 'Anthropic',
    modelName: 'claude-sonnet-5-202606',
    displayName: 'Claude Sonnet 5',
    modelFamily: 'Claude 5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'Anthropic Claude 5 (2026)',
    notes: 'Agentic daily driver (June 30, 2026) balancing deep reasoning with high throughput and 1M context.',
    aaIntelligenceIndex: 93.8,
    aaModelId: 'claude-sonnet-5',
    aaEvaluations: {
      gpqa: 80.2,
      math: 96.5,
      coding: 95.8,
      throughputTokSec: 88.0,
      priceInputPer1M: 2.5,
      priceOutputPer1M: 12.5,
    },
  },
  {
    id: 'claude-fable-5',
    name: '🎨 Claude Fable 5 (Long-Horizon Agentic)',
    provider: 'Anthropic',
    modelName: 'claude-fable-5-202606',
    displayName: 'Claude Fable 5',
    modelFamily: 'Claude 5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: false,
    categoryTag: 'Anthropic Claude 5 (2026)',
    notes: 'Mythos-architecture model (June 9, 2026) engineered for long-horizon agentic task completion and UI synthesis.',
    aaIntelligenceIndex: 92.0,
    aaModelId: 'claude-fable-5',
    aaEvaluations: {
      gpqa: 76.0,
      math: 92.0,
      coding: 94.0,
      throughputTokSec: 75.0,
      priceInputPer1M: 2.0,
      priceOutputPer1M: 10.0,
    },
  },
  {
    id: 'claude-haiku-4-5',
    name: '⚡ Claude Haiku 4.5',
    provider: 'Anthropic',
    modelName: 'claude-haiku-4-5-202601',
    displayName: 'Claude Haiku 4.5',
    modelFamily: 'Claude 4.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: false,
    categoryTag: 'Anthropic Claude 5 (2026)',
    notes: 'High-speed compact generation model for quick UI prototyping and validation.',
    aaIntelligenceIndex: 78.5,
    aaModelId: 'claude-haiku-4-5',
    aaEvaluations: {
      gpqa: 62.0,
      math: 78.0,
      coding: 86.0,
      throughputTokSec: 145.0,
      priceInputPer1M: 0.5,
      priceOutputPer1M: 2.5,
    },
  },

  // ==========================================
  // 🌟 OPENAI GPT-5.6 & GPT-5 GENERATION (2026)
  // ==========================================
  {
    id: 'gpt-5-6-sol',
    name: '🌟 OpenAI GPT-5.6 Sol (Flagship Reasoning)',
    provider: 'OpenAI',
    modelName: 'gpt-5.6-sol-202607',
    displayName: 'OpenAI GPT-5.6 Sol',
    modelFamily: 'GPT-5.6',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'OpenAI GPT-5.6 (2026)',
    notes: 'Top-tier frontier reasoning model (July 2026) with integrated thinking and SOTA fullstack code synthesis.',
    aaIntelligenceIndex: 96.8,
    aaModelId: 'gpt-5-6-sol',
    aaEvaluations: {
      gpqa: 85.2,
      math: 99.1,
      coding: 97.5,
      throughputTokSec: 65.0,
      priceInputPer1M: 5.0,
      priceOutputPer1M: 20.0,
    },
  },
  {
    id: 'gpt-5-6-terra',
    name: '🌟 OpenAI GPT-5.6 Terra (Balanced)',
    provider: 'OpenAI',
    modelName: 'gpt-5.6-terra-202607',
    displayName: 'OpenAI GPT-5.6 Terra',
    modelFamily: 'GPT-5.6',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '500k',
    isReasoningModel: false,
    categoryTag: 'OpenAI GPT-5.6 (2026)',
    notes: 'Mainstream high-speed workhorse model (July 2026) engineered for interactive UI generation.',
    aaIntelligenceIndex: 92.5,
    aaModelId: 'gpt-5-6-terra',
    aaEvaluations: {
      gpqa: 78.4,
      math: 94.0,
      coding: 95.0,
      throughputTokSec: 95.0,
      priceInputPer1M: 2.0,
      priceOutputPer1M: 8.0,
    },
  },
  {
    id: 'gpt-5-6-luna',
    name: '🌟 OpenAI GPT-5.6 Luna (Fast & Efficient)',
    provider: 'OpenAI',
    modelName: 'gpt-5.6-luna-202607',
    displayName: 'OpenAI GPT-5.6 Luna',
    modelFamily: 'GPT-5.6',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '256k',
    isReasoningModel: false,
    categoryTag: 'OpenAI GPT-5.6 (2026)',
    notes: 'Low-latency, cost-effective model optimized for high-volume benchmark testing.',
    aaIntelligenceIndex: 82.0,
    aaModelId: 'gpt-5-6-luna',
    aaEvaluations: {
      gpqa: 66.0,
      math: 86.0,
      coding: 88.0,
      throughputTokSec: 160.0,
      priceInputPer1M: 0.25,
      priceOutputPer1M: 1.0,
    },
  },
  {
    id: 'gpt-5-5-thinking',
    name: '🌟 OpenAI GPT-5.5 (Thinking Mode)',
    provider: 'OpenAI',
    modelName: 'gpt-5.5-202603',
    displayName: 'OpenAI GPT-5.5 (Thinking)',
    modelFamily: 'GPT-5.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '500k',
    isReasoningModel: true,
    categoryTag: 'OpenAI GPT-5.6 (2026)',
    notes: 'Professional reasoning model with deep verification paths for complex algorithmic synthesis.',
    aaIntelligenceIndex: 94.2,
    aaModelId: 'gpt-5-5',
    aaEvaluations: {
      gpqa: 81.0,
      math: 97.4,
      coding: 95.5,
      throughputTokSec: 72.0,
      priceInputPer1M: 3.5,
      priceOutputPer1M: 14.0,
    },
  },

  // ==========================================
  // ⚡ DEEPSEEK V4 GENERATION (AUGUST 2026)
  // ==========================================
  {
    id: 'deepseek-v4-pro',
    name: '⚡ DeepSeek-V4-Pro (1.6T MoE GA)',
    provider: 'DeepSeek',
    modelName: 'deepseek-v4-pro-0813',
    displayName: 'DeepSeek-V4-Pro',
    modelFamily: 'DeepSeek V4',
    parameterCount: 'MoE 1.6T (49B active)',
    architecture: 'Transformer + Multi-Head Latent Attention (MLA)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'DeepSeek V4 (2026)',
    notes: 'DeepSeek flagship GA release (August 13, 2026) with 1.6T total params, 1M context, and integrated reasoning.',
    aaIntelligenceIndex: 95.0,
    aaModelId: 'deepseek-v4-pro',
    aaEvaluations: {
      gpqa: 82.5,
      math: 98.4,
      coding: 96.5,
      throughputTokSec: 54.0,
      priceInputPer1M: 0.45,
      priceOutputPer1M: 1.8,
    },
  },
  {
    id: 'deepseek-v4-flash',
    name: '⚡ DeepSeek-V4-Flash (High Speed)',
    provider: 'DeepSeek',
    modelName: 'deepseek-v4-flash-202607',
    displayName: 'DeepSeek-V4-Flash',
    modelFamily: 'DeepSeek V4',
    parameterCount: 'MoE 480B (24B active)',
    architecture: 'Transformer + Multi-Head Latent Attention (MLA)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '500k',
    isReasoningModel: false,
    categoryTag: 'DeepSeek V4 (2026)',
    notes: 'Public beta release (July 31, 2026) engineered for high-throughput, low-cost code streaming.',
    aaIntelligenceIndex: 88.5,
    aaModelId: 'deepseek-v4-flash',
    aaEvaluations: {
      gpqa: 72.0,
      math: 92.5,
      coding: 91.0,
      throughputTokSec: 115.0,
      priceInputPer1M: 0.15,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'deepseek-v4-coder',
    name: '⚡ DeepSeek-V4-Coder',
    provider: 'DeepSeek',
    modelName: 'deepseek-v4-coder-202608',
    displayName: 'DeepSeek-V4-Coder',
    modelFamily: 'DeepSeek V4',
    parameterCount: 'MoE 680B (32B active)',
    architecture: 'Transformer + Multi-Head Latent Attention (MLA)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '500k',
    isReasoningModel: false,
    categoryTag: 'DeepSeek V4 (2026)',
    notes: 'Dedicated software engineering and HTML5/WebGL frontend code synthesis specialist.',
    aaIntelligenceIndex: 91.0,
    aaModelId: 'deepseek-v4-coder',
    aaEvaluations: {
      gpqa: 75.0,
      math: 94.0,
      coding: 96.0,
      throughputTokSec: 80.0,
      priceInputPer1M: 0.2,
      priceOutputPer1M: 0.8,
    },
  },
  {
    id: 'deepseek-v4-lite-32b',
    name: '⚡ DeepSeek-V4-Lite 32B (Local)',
    provider: 'DeepSeek',
    modelName: 'deepseek-v4-lite:32b',
    displayName: 'DeepSeek-V4-Lite 32B',
    modelFamily: 'DeepSeek V4',
    parameterCount: '32B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'DeepSeek V4 (2026)',
    notes: 'Dense 32B model with distilled V4 reasoning capabilities for local inference.',
    aaIntelligenceIndex: 83.2,
    aaModelId: 'deepseek-v4-lite-32b',
    aaEvaluations: {
      gpqa: 68.0,
      math: 93.0,
      coding: 90.0,
      throughputTokSec: 46.0,
      priceInputPer1M: 0.2,
      priceOutputPer1M: 0.6,
    },
  },

  // ==========================================
  // 🔮 GOOGLE GEMINI 3.7 & 3.1 GENERATION (2026)
  // ==========================================
  {
    id: 'gemini-3-7-flash',
    name: '🔮 Google Gemini 3.7 Flash (Aug 2026 Leader)',
    provider: 'Google',
    modelName: 'gemini-3.7-flash-20260813',
    displayName: 'Gemini 3.7 Flash',
    modelFamily: 'Gemini 3.7',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '2M',
    isReasoningModel: true,
    categoryTag: 'Google Gemini 3.x (2026)',
    notes: 'Latest Google release (August 13, 2026) featuring algorithmic improvements in coding, agentic reasoning, and 2M context.',
    aaIntelligenceIndex: 94.6,
    aaModelId: 'gemini-3-7-flash',
    aaEvaluations: {
      gpqa: 81.5,
      math: 97.8,
      coding: 96.2,
      throughputTokSec: 165.0,
      priceInputPer1M: 0.15,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'gemini-3-1-pro',
    name: '🔮 Google Gemini 3.1 Pro (1M Context)',
    provider: 'Google',
    modelName: 'gemini-3.1-pro-20260219',
    displayName: 'Gemini 3.1 Pro',
    modelFamily: 'Gemini 3.1',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'Google Gemini 3.x (2026)',
    notes: 'Google core reasoning flagship (February 19, 2026) optimized for deep reasoning, ARC-AGI-2 (77.1%), and agentic tool orchestration.',
    aaIntelligenceIndex: 93.5,
    aaModelId: 'gemini-3-1-pro',
    aaEvaluations: {
      gpqa: 79.5,
      math: 96.5,
      coding: 94.8,
      throughputTokSec: 75.0,
      priceInputPer1M: 1.25,
      priceOutputPer1M: 5.0,
    },
  },
  {
    id: 'gemini-3-1-flash',
    name: '🔮 Google Gemini 3.1 Flash',
    provider: 'Google',
    modelName: 'gemini-3.1-flash',
    displayName: 'Gemini 3.1 Flash',
    modelFamily: 'Gemini 3.1',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: false,
    categoryTag: 'Google Gemini 3.x (2026)',
    notes: 'High-speed, low-latency multimodal production model with 1M token context.',
    aaIntelligenceIndex: 86.8,
    aaModelId: 'gemini-3-1-flash',
    aaEvaluations: {
      gpqa: 70.0,
      math: 91.0,
      coding: 89.5,
      throughputTokSec: 155.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.4,
    },
  },
  {
    id: 'gemini-3-0-pro',
    name: '🔮 Google Gemini 3.0 Pro (Deep Think)',
    provider: 'Google',
    modelName: 'gemini-3.0-pro',
    displayName: 'Gemini 3.0 Pro',
    modelFamily: 'Gemini 3.0',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'Google Gemini 3.x (2026)',
    notes: 'Introduced Deep Think mode and native multimodal planning.',
    aaIntelligenceIndex: 88.5,
    aaModelId: 'gemini-3-0-pro',
    aaEvaluations: {
      gpqa: 73.0,
      math: 93.0,
      coding: 91.0,
      throughputTokSec: 80.0,
      priceInputPer1M: 1.0,
      priceOutputPer1M: 4.0,
    },
  },
  {
    id: 'gemini-2-5-pro',
    name: '🔮 Google Gemini 2.5 Pro (Thinking Model)',
    provider: 'Google',
    modelName: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    modelFamily: 'Gemini 2.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'Google Gemini 3.x (2026)',
    notes: 'Google pioneering reasoning model with thought verification before responding.',
    aaIntelligenceIndex: 85.0,
    aaModelId: 'gemini-2-5-pro',
    aaEvaluations: {
      gpqa: 68.0,
      math: 89.0,
      coding: 88.0,
      throughputTokSec: 70.0,
      priceInputPer1M: 1.0,
      priceOutputPer1M: 4.0,
    },
  },

  // ==========================================
  // 💻 ALIBABA QWEN 3.8 & QWEN 3 GENERATION (2026)
  // ==========================================
  {
    id: 'qwen-3-8-max',
    name: '💻 Qwen 3.8-Max (2.4T MoE Flagship)',
    provider: 'Alibaba',
    modelName: 'qwen-3.8-max-20260719',
    displayName: 'Qwen 3.8-Max',
    modelFamily: 'Qwen 3.8',
    parameterCount: '2.4T MoE',
    architecture: 'Mixture of Experts (MoE)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'Alibaba Qwen 3.8 (2026)',
    notes: 'Massive 2.4-trillion-parameter flagship (July 19, 2026) leading open-access benchmarks.',
    aaIntelligenceIndex: 94.0,
    aaModelId: 'qwen-3-8-max',
    aaEvaluations: {
      gpqa: 80.5,
      math: 97.0,
      coding: 95.4,
      throughputTokSec: 45.0,
      priceInputPer1M: 1.8,
      priceOutputPer1M: 5.4,
    },
  },
  {
    id: 'qwen-3-8-27b-local',
    name: '💻 Qwen 3.8-27B Instruct (Aug 2026 Open)',
    provider: 'Alibaba',
    modelName: 'qwen3.8:27b-20260814',
    displayName: 'Qwen 3.8-27B',
    modelFamily: 'Qwen 3.8',
    parameterCount: '27B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Alibaba Qwen 3.8 (2026)',
    notes: 'Freshly released (August 14, 2026) open-weights powerhouse designed for local consumer hardware.',
    aaIntelligenceIndex: 82.5,
    aaModelId: 'qwen-3-8-27b',
    aaEvaluations: {
      gpqa: 67.0,
      math: 91.0,
      coding: 91.5,
      throughputTokSec: 52.0,
      priceInputPer1M: 0.15,
      priceOutputPer1M: 0.45,
    },
  },
  {
    id: 'qwen-3-8-coder-32b',
    name: '💻 Qwen 3.8-Coder 32B Instruct',
    provider: 'Alibaba',
    modelName: 'qwen3.8-coder:32b',
    displayName: 'Qwen 3.8-Coder 32B',
    modelFamily: 'Qwen 3.8',
    parameterCount: '32B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Alibaba Qwen 3.8 (2026)',
    notes: 'Top-ranking local code generation model with near-GPT-5 level frontend coding capability.',
    aaIntelligenceIndex: 85.2,
    aaModelId: 'qwen-3-8-coder-32b',
    aaEvaluations: {
      gpqa: 70.0,
      math: 93.5,
      coding: 94.2,
      throughputTokSec: 44.0,
      priceInputPer1M: 0.2,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'qwq-2-0-thinking',
    name: '🧠 QwQ 2.0 (64B Reasoning)',
    provider: 'Alibaba',
    modelName: 'qwq-2.0-thinking',
    displayName: 'QwQ 2.0 Thinking (64B)',
    modelFamily: 'QwQ',
    parameterCount: '70B',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'Alibaba Qwen 3.8 (2026)',
    notes: 'Full reasoning open model with extended verification paths.',
    aaIntelligenceIndex: 88.0,
    aaModelId: 'qwq-2-0',
    aaEvaluations: {
      gpqa: 74.0,
      math: 96.0,
      coding: 93.0,
      throughputTokSec: 30.0,
      priceInputPer1M: 0.4,
      priceOutputPer1M: 1.2,
    },
  },

  // ==========================================
  // ⚡ XAI GROK 4 SERIES (AUGUST 2026)
  // ==========================================
  {
    id: 'grok-4-6',
    name: '⚡ xAI Grok 4.6 (Aug 2026 Flagship)',
    provider: 'xAI',
    modelName: 'grok-4.6-20260812',
    displayName: 'xAI Grok 4.6',
    modelFamily: 'Grok 4',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '500k',
    isReasoningModel: true,
    categoryTag: 'xAI Grok 4 (2026)',
    notes: 'Officially launched August 12, 2026. SOTA flagship model with 500k context optimized for agentic coding and complex logic.',
    aaIntelligenceIndex: 95.8,
    aaModelId: 'grok-4-6',
    aaEvaluations: {
      gpqa: 84.0,
      math: 98.6,
      coding: 96.8,
      throughputTokSec: 72.0,
      priceInputPer1M: 4.0,
      priceOutputPer1M: 16.0,
    },
  },
  {
    id: 'grok-4-5-flash',
    name: '⚡ xAI Grok 4.5 Flash',
    provider: 'xAI',
    modelName: 'grok-4.5-flash',
    displayName: 'xAI Grok 4.5 Flash',
    modelFamily: 'Grok 4',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '256k',
    isReasoningModel: false,
    categoryTag: 'xAI Grok 4 (2026)',
    notes: 'High-velocity streaming model with sub-second time to first token.',
    aaIntelligenceIndex: 88.0,
    aaModelId: 'grok-4-5-flash',
    aaEvaluations: {
      gpqa: 71.0,
      math: 91.0,
      coding: 91.5,
      throughputTokSec: 140.0,
      priceInputPer1M: 0.5,
      priceOutputPer1M: 2.0,
    },
  },

  // ==========================================
  // 🦙 META LLAMA 4 & MUSE (2025/2026)
  // ==========================================
  {
    id: 'llama-4-scout',
    name: '🦙 Meta Llama 4 Scout (MoE)',
    provider: 'Meta',
    modelName: 'llama4-scout',
    displayName: 'Llama 4 Scout',
    modelFamily: 'Llama 4',
    parameterCount: 'MoE 400B (32B active)',
    architecture: 'Mixture of Experts (MoE)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'local',
    contextWindow: '256k',
    isReasoningModel: false,
    categoryTag: 'Meta Llama 4 (2025/2026)',
    notes: 'Meta Llama 4 MoE architecture delivering enterprise coding speed.',
    aaIntelligenceIndex: 86.5,
    aaModelId: 'llama-4-scout',
    aaEvaluations: {
      gpqa: 72.0,
      math: 92.0,
      coding: 91.0,
      throughputTokSec: 65.0,
      priceInputPer1M: 0.5,
      priceOutputPer1M: 1.5,
    },
  },
  {
    id: 'llama-4-maverick',
    name: '🦙 Meta Llama 4 Maverick (Dense)',
    provider: 'Meta',
    modelName: 'llama4-maverick',
    displayName: 'Llama 4 Maverick',
    modelFamily: 'Llama 4',
    parameterCount: '70B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '256k',
    isReasoningModel: false,
    categoryTag: 'Meta Llama 4 (2025/2026)',
    notes: 'Dense Llama 4 flagship model designed for local high-precision inference.',
    aaIntelligenceIndex: 84.0,
    aaModelId: 'llama-4-maverick',
    aaEvaluations: {
      gpqa: 68.5,
      math: 89.0,
      coding: 89.5,
      throughputTokSec: 38.0,
      priceInputPer1M: 0.35,
      priceOutputPer1M: 1.0,
    },
  },
  {
    id: 'meta-muse-spark',
    name: '🦙 Meta Muse Spark (April 2026 Reasoning)',
    provider: 'Meta',
    modelName: 'meta-muse-spark-202604',
    displayName: 'Meta Muse Spark',
    modelFamily: 'Meta Muse',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '500k',
    isReasoningModel: true,
    categoryTag: 'Meta Llama 4 (2025/2026)',
    notes: 'Meta high-end reasoning model (April 2026) trained with reinforcement learning on verified code execution.',
    aaIntelligenceIndex: 93.0,
    aaModelId: 'meta-muse-spark',
    aaEvaluations: {
      gpqa: 79.0,
      math: 96.5,
      coding: 95.0,
      throughputTokSec: 60.0,
      priceInputPer1M: 2.0,
      priceOutputPer1M: 8.0,
    },
  },

  // ==========================================
  // 🌪️ MISTRAL AI (2026 GENERATION)
  // ==========================================
  {
    id: 'mistral-large-3',
    name: '🌪️ Mistral Large 3 (675B MoE Apache 2.0)',
    provider: 'Mistral AI',
    modelName: 'mistral-large-3-202512',
    displayName: 'Mistral Large 3',
    modelFamily: 'Mistral Large',
    parameterCount: 'MoE 675B (41B active)',
    architecture: 'Mixture of Experts (MoE)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '256k',
    isReasoningModel: false,
    categoryTag: 'Mistral AI (2026)',
    notes: 'Mistral largest open flagship model with 675B total parameters released under Apache 2.0.',
    aaIntelligenceIndex: 89.2,
    aaModelId: 'mistral-large-3',
    aaEvaluations: {
      gpqa: 73.0,
      math: 92.0,
      coding: 93.0,
      throughputTokSec: 64.0,
      priceInputPer1M: 1.5,
      priceOutputPer1M: 4.5,
    },
  },
  {
    id: 'mistral-small-4',
    name: '🌪️ Mistral Small 4 (March 2026 Reasoning)',
    provider: 'Mistral AI',
    modelName: 'mistral-small-4-20260316',
    displayName: 'Mistral Small 4',
    modelFamily: 'Mistral Small',
    parameterCount: '27B',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'Mistral AI (2026)',
    notes: 'Consolidated high-speed reasoning model (March 16, 2026) with SOTA efficiency.',
    aaIntelligenceIndex: 82.8,
    aaModelId: 'mistral-small-4',
    aaEvaluations: {
      gpqa: 66.0,
      math: 88.0,
      coding: 89.0,
      throughputTokSec: 85.0,
      priceInputPer1M: 0.25,
      priceOutputPer1M: 0.75,
    },
  },
  {
    id: 'codestral-2601',
    name: '🌪️ Mistral Codestral 2601',
    provider: 'Mistral AI',
    modelName: 'codestral-2601',
    displayName: 'Codestral 26.01',
    modelFamily: 'Codestral',
    parameterCount: '32B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '256k',
    isReasoningModel: false,
    categoryTag: 'Mistral AI (2026)',
    notes: 'Specialized 256k context frontend coding and FIM (Fill-in-the-Middle) model.',
    aaIntelligenceIndex: 84.5,
    aaModelId: 'codestral-2601',
    aaEvaluations: {
      gpqa: 67.0,
      math: 89.0,
      coding: 93.8,
      throughputTokSec: 95.0,
      priceInputPer1M: 0.3,
      priceOutputPer1M: 0.9,
    },
  },

  // ==========================================
  // 🚀 MOONSHOT KIMI, MINIMAX & 01.AI (2026)
  // ==========================================
  {
    id: 'kimi-k3',
    name: '🚀 Moonshot Kimi K3 (2.8T MoE July 2026)',
    provider: 'Moonshot AI (Kimi)',
    modelName: 'kimi-k3-202607',
    displayName: 'Kimi K3 (2.8T MoE)',
    modelFamily: 'Kimi K3',
    parameterCount: '2.8T MoE',
    architecture: 'Mixture of Experts (MoE)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'Global Frontier Labs (2026)',
    notes: 'Moonshot AI frontier flagship (July 2026) with 2.8T parameters, 1M context, and agent swarm orchestration.',
    aaIntelligenceIndex: 94.8,
    aaModelId: 'kimi-k3',
    aaEvaluations: {
      gpqa: 82.0,
      math: 97.5,
      coding: 96.0,
      throughputTokSec: 58.0,
      priceInputPer1M: 1.8,
      priceOutputPer1M: 6.0,
    },
  },
  {
    id: 'kimi-k2-7-code',
    name: '🚀 Moonshot Kimi K2.7 Code',
    provider: 'Moonshot AI (Kimi)',
    modelName: 'kimi-k2.7-code',
    displayName: 'Kimi K2.7 Code',
    modelFamily: 'Kimi K2',
    parameterCount: 'MoE 1T (32B active)',
    architecture: 'Mixture of Experts (MoE)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: false,
    categoryTag: 'Global Frontier Labs (2026)',
    notes: 'Specialized coding model (June 2026) with high instruction-following in long contexts.',
    aaIntelligenceIndex: 90.2,
    aaModelId: 'kimi-k2-7-code',
    aaEvaluations: {
      gpqa: 74.0,
      math: 93.0,
      coding: 95.0,
      throughputTokSec: 75.0,
      priceInputPer1M: 1.0,
      priceOutputPer1M: 3.5,
    },
  },
  {
    id: 'minimax-m3',
    name: '🌌 MiniMax M3 (Omni-Modal 1M Context)',
    provider: 'MiniMax',
    modelName: 'minimax-m3-202605',
    displayName: 'MiniMax M3',
    modelFamily: 'MiniMax M3',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'Global Frontier Labs (2026)',
    notes: 'Natively multimodal omni foundation model (May 2026) with MiniMax Sparse Attention (MSA).',
    aaIntelligenceIndex: 91.5,
    aaModelId: 'minimax-m3',
    aaEvaluations: {
      gpqa: 76.0,
      math: 94.5,
      coding: 94.0,
      throughputTokSec: 85.0,
      priceInputPer1M: 0.6,
      priceOutputPer1M: 2.2,
    },
  },
  {
    id: 'yi-lightning',
    name: '⚡ 01.AI Yi-Lightning (High-Speed MoE)',
    provider: '01.AI (Yi)',
    modelName: 'yi-lightning',
    displayName: 'Yi-Lightning',
    modelFamily: 'Yi-Lightning',
    parameterCount: 'MoE 670B (36B active)',
    architecture: 'Mixture of Experts (MoE)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Global Frontier Labs (2026)',
    notes: '01.AI high-performance MoE model ranking at the top of global math and coding leaderboards.',
    aaIntelligenceIndex: 89.0,
    aaModelId: 'yi-lightning',
    aaEvaluations: {
      gpqa: 73.0,
      math: 92.5,
      coding: 93.0,
      throughputTokSec: 90.0,
      priceInputPer1M: 0.35,
      priceOutputPer1M: 1.0,
    },
  },

  // ==========================================
  // 🔬 MICROSOFT PHI, COHERE & ENTERPRISE (2026)
  // ==========================================
  {
    id: 'phi-4-reasoning-vision-15b',
    name: '🔬 Microsoft Phi-4-Reasoning-Vision (15B)',
    provider: 'Microsoft',
    modelName: 'phi4-reasoning-vision:15b-202603',
    displayName: 'Phi-4 Reasoning-Vision 15B',
    modelFamily: 'Phi-4',
    parameterCount: '14B',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '64k',
    isReasoningModel: true,
    categoryTag: 'Microsoft & Enterprise (2026)',
    notes: 'Launched March 2026. Compact 15B multimodal model with deep synthetic reasoning.',
    aaIntelligenceIndex: 80.5,
    aaModelId: 'phi-4-reasoning-vision-15b',
    aaEvaluations: {
      gpqa: 64.0,
      math: 89.0,
      coding: 88.0,
      throughputTokSec: 70.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.3,
    },
  },
  {
    id: 'phi-4-5-mini',
    name: '🔬 Microsoft Phi-4.5 Mini (4B)',
    provider: 'Microsoft',
    modelName: 'phi4.5-mini:4b',
    displayName: 'Microsoft Phi-4.5 Mini',
    modelFamily: 'Phi-4',
    parameterCount: '3B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Microsoft & Enterprise (2026)',
    notes: 'Ultra-compact on-device model capable of 128k context and high code fidelity.',
    aaIntelligenceIndex: 66.0,
    aaModelId: 'phi-4-5-mini',
    aaEvaluations: {
      gpqa: 46.0,
      math: 76.0,
      coding: 77.0,
      throughputTokSec: 150.0,
      priceInputPer1M: 0.03,
      priceOutputPer1M: 0.09,
    },
  },
  {
    id: 'amazon-nova-pro-2',
    name: '📦 Amazon Nova Pro 2 (500k Context)',
    provider: 'Amazon Bedrock',
    modelName: 'amazon.nova-pro-v2:0',
    displayName: 'Amazon Nova Pro 2',
    modelFamily: 'Amazon Nova',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '500k',
    isReasoningModel: false,
    categoryTag: 'Microsoft & Enterprise (2026)',
    notes: 'Amazon frontier enterprise multimodal foundation model with 500k context.',
    aaIntelligenceIndex: 87.0,
    aaModelId: 'amazon-nova-pro-v2',
    aaEvaluations: {
      gpqa: 70.0,
      math: 89.0,
      coding: 91.0,
      throughputTokSec: 85.0,
      priceInputPer1M: 0.8,
      priceOutputPer1M: 3.2,
    },
  },
  {
    id: 'cohere-command-r-plus-plus',
    name: '🌐 Cohere Command R++ (2026)',
    provider: 'Cohere',
    modelName: 'command-r-plus-plus-2026',
    displayName: 'Command R++ (2026)',
    modelFamily: 'Command R++',
    parameterCount: '120B+',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '256k',
    isReasoningModel: false,
    categoryTag: 'Microsoft & Enterprise (2026)',
    notes: 'Enterprise agentic workflow and multilingual code synthesis engine.',
    aaIntelligenceIndex: 83.5,
    aaModelId: 'command-r-plus-plus',
    aaEvaluations: {
      gpqa: 65.0,
      math: 82.0,
      coding: 88.0,
      throughputTokSec: 65.0,
      priceInputPer1M: 2.0,
      priceOutputPer1M: 8.0,
    },
  },

  // ==========================================
  // 📜 CLASSIC & MILESTONE BASELINES
  // ==========================================
  {
    id: 'claude-3-7-sonnet',
    name: '📜 Claude 3.7 Sonnet (2025 Milestone)',
    provider: 'Anthropic',
    modelName: 'claude-3-7-sonnet-20250219',
    displayName: 'Claude 3.7 Sonnet',
    modelFamily: 'Claude 3.7',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: true,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'Historic first hybrid-thinking frontier model by Anthropic (Feb 2025).',
    aaIntelligenceIndex: 91.8,
    aaModelId: 'claude-3-7-sonnet',
    aaEvaluations: {
      gpqa: 75.8,
      math: 96.2,
      coding: 94.0,
      throughputTokSec: 68.0,
      priceInputPer1M: 3.0,
      priceOutputPer1M: 15.0,
    },
  },
  {
    id: 'claude-3-5-sonnet-v2',
    name: '📜 Claude 3.5 Sonnet v2 (Canvas & 3D Benchmark)',
    provider: 'Anthropic',
    modelName: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet v2',
    modelFamily: 'Claude 3.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: false,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'Long-standing gold standard for single-file HTML5, Canvas, and 3D WebGL generation.',
    aaIntelligenceIndex: 82.3,
    aaModelId: 'claude-3-5-sonnet',
    aaEvaluations: {
      gpqa: 65.0,
      math: 78.3,
      coding: 92.0,
      throughputTokSec: 74.0,
      priceInputPer1M: 3.0,
      priceOutputPer1M: 15.0,
    },
  },
  {
    id: 'gpt-4o',
    name: '📜 OpenAI GPT-4o (Omni Baseline)',
    provider: 'OpenAI',
    modelName: 'gpt-4o-2024-11-20',
    displayName: 'OpenAI GPT-4o',
    modelFamily: 'GPT-4o',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'Foundational omni multimodal model.',
    aaIntelligenceIndex: 81.0,
    aaModelId: 'gpt-4o',
    aaEvaluations: {
      gpqa: 53.6,
      math: 76.6,
      coding: 88.0,
      throughputTokSec: 85.0,
      priceInputPer1M: 2.5,
      priceOutputPer1M: 10.0,
    },
  },
  {
    id: 'gpt-4o-mini',
    name: '📜 OpenAI GPT-4o mini',
    provider: 'OpenAI',
    modelName: 'gpt-4o-mini',
    displayName: 'OpenAI GPT-4o mini',
    modelFamily: 'GPT-4o',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'Lightweight efficient generation baseline.',
    aaIntelligenceIndex: 64.5,
    aaModelId: 'gpt-4o-mini',
    aaEvaluations: {
      gpqa: 40.2,
      math: 70.2,
      coding: 72.0,
      throughputTokSec: 130.0,
      priceInputPer1M: 0.15,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'deepseek-r1',
    name: '📜 DeepSeek R1 (671B RL Milestone)',
    provider: 'DeepSeek',
    modelName: 'deepseek-reasoner',
    displayName: 'DeepSeek R1',
    modelFamily: 'DeepSeek R1',
    parameterCount: 'MoE 671B (37B active)',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'Historic open-weights RL reasoning breakthrough model.',
    aaIntelligenceIndex: 88.6,
    aaModelId: 'deepseek-r1',
    aaEvaluations: {
      gpqa: 71.5,
      math: 97.3,
      coding: 89.2,
      throughputTokSec: 28.5,
      priceInputPer1M: 0.55,
      priceOutputPer1M: 2.19,
    },
  },
  {
    id: 'deepseek-v3',
    name: '📜 DeepSeek V3 (671B MoE MLA)',
    provider: 'DeepSeek',
    modelName: 'deepseek-chat',
    displayName: 'DeepSeek V3',
    modelFamily: 'DeepSeek V3',
    parameterCount: 'MoE 671B (37B active)',
    architecture: 'Transformer + Multi-Head Latent Attention (MLA)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'High-throughput sparse MoE baseline architecture.',
    aaIntelligenceIndex: 78.4,
    aaModelId: 'deepseek-v3',
    aaEvaluations: {
      gpqa: 59.1,
      math: 89.3,
      coding: 84.1,
      throughputTokSec: 62.0,
      priceInputPer1M: 0.27,
      priceOutputPer1M: 1.1,
    },
  },
  {
    id: 'gemini-2-0-flash',
    name: '📜 Google Gemini 2.0 Flash',
    provider: 'Google',
    modelName: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash',
    modelFamily: 'Gemini 2.0',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: false,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'High speed 1M context multimodal benchmark model.',
    aaIntelligenceIndex: 78.9,
    aaModelId: 'gemini-2-0-flash',
    aaEvaluations: {
      gpqa: 62.1,
      math: 84.0,
      coding: 82.5,
      throughputTokSec: 150.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.4,
    },
  },
  {
    id: 'llama-3-3-70b',
    name: '📜 Meta Llama 3.3 70B Instruct',
    provider: 'Meta',
    modelName: 'llama3.3:70b',
    displayName: 'Llama 3.3 70B',
    modelFamily: 'Llama 3.3',
    parameterCount: '70B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'Dense 70B open weights reference standard.',
    aaIntelligenceIndex: 76.5,
    aaModelId: 'llama-3-3-70b-instruct',
    aaEvaluations: {
      gpqa: 54.0,
      math: 81.0,
      coding: 83.2,
      throughputTokSec: 32.0,
      priceInputPer1M: 0.35,
      priceOutputPer1M: 1.0,
    },
  },
  {
    id: 'qwen-2-5-coder-32b',
    name: '📜 Qwen 2.5 Coder 32B Instruct',
    provider: 'Alibaba',
    modelName: 'qwen2.5-coder:32b',
    displayName: 'Qwen 2.5 Coder 32B',
    modelFamily: 'Qwen 2.5',
    parameterCount: '32B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'Dense 32B code model open standard.',
    aaIntelligenceIndex: 74.2,
    aaModelId: 'qwen-2-5-coder-32b-instruct',
    aaEvaluations: {
      gpqa: 48.0,
      math: 82.0,
      coding: 86.5,
      throughputTokSec: 42.0,
      priceInputPer1M: 0.2,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'smollm2-1-7b',
    name: '📜 SmolLM2 1.7B Instruct',
    provider: 'Hugging Face',
    modelName: 'smollm2:1.7b',
    displayName: 'SmolLM2 1.7B',
    modelFamily: 'SmolLM2',
    parameterCount: '1.5B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '8k',
    isReasoningModel: false,
    categoryTag: 'Classic & Milestone Baselines',
    notes: 'Ultra-lightweight edge computing benchmark.',
    aaIntelligenceIndex: 42.0,
    aaModelId: 'smollm2-1-7b',
    aaEvaluations: {
      gpqa: 20.0,
      math: 35.0,
      coding: 48.0,
      throughputTokSec: 180.0,
      priceInputPer1M: 0.01,
      priceOutputPer1M: 0.03,
    },
  },
];
