export interface ModelPresetTemplate {
  id: string;
  name: string;
  provider: string;
  modelName: string;
  displayName: string;
  modelFamily: string;
  parameterCount: string;
  architecture: string;
  quantization: string;
  localOrCloud: 'cloud' | 'local';
  contextWindow: string;
  isReasoningModel: boolean;
  notes: string;
  categoryTag?: string;
  // Artificial Analysis benchmark data
  aaIntelligenceIndex?: number;
  aaModelId?: string;
  aaEvaluations?: {
    gpqa?: number;
    math?: number;
    coding?: number;
    throughputTokSec?: number;
    priceInputPer1M?: number;
    priceOutputPer1M?: number;
  };
}

export const PROVIDER_CATEGORIES = [
  {
    category: 'Frontier Cloud Labs',
    providers: [
      'Anthropic',
      'OpenAI',
      'Google',
      'DeepSeek',
      'xAI',
      'Meta',
      'Mistral AI',
      'Cohere',
      'Alibaba',
      'Amazon Bedrock',
      'Microsoft',
    ],
  },
  {
    category: 'Local Inference Engines',
    providers: [
      'Ollama',
      'LM Studio',
      'vLLM',
      'SGLang',
      'LocalAI',
      'llama.cpp',
      'Jan',
      'ExLlamaV2',
      'Local / Self-Hosted',
    ],
  },
  {
    category: 'Cloud Gateways & Aggregators',
    providers: [
      'OpenRouter',
      'Together AI',
      'Groq',
      'Fireworks AI',
      'Cerebras',
      'DeepInfra',
      'Hugging Face',
      'Perplexity',
      'Novita AI',
    ],
  },
];

export const ALL_COMMON_PROVIDERS = PROVIDER_CATEGORIES.flatMap((c) => c.providers);

export const ARCHITECTURE_PRESETS = [
  { label: 'Transformer (Decoder-only Dense)', desc: 'Standard autoregressive dense transformer architecture' },
  { label: 'Mixture of Experts (MoE)', desc: 'Sparse gated mixture of experts (e.g. Mixtral, Qwen Max, DBRX)' },
  { label: 'Transformer + Multi-Head Latent Attention (MLA)', desc: 'DeepSeek V2/V3 low-memory KV cache architecture' },
  { label: 'Reasoning / Thinking Model', desc: 'Chain-of-thought specialized model (o1, o3, R1, QwQ)' },
  { label: 'Hybrid SSM-Transformer (Mamba / Jamba)', desc: 'State-space model fused with attention layers' },
  { label: 'State Space / Linear RNN (RWKV)', desc: 'Non-transformer linear attention / recurrent architecture' },
  { label: 'Vision-Language Multimodal (VLM)', desc: 'Joint vision and language encoder-decoder' },
  { label: 'Diffusion / Diffusion-Transformer', desc: 'Continuous diffusion based generation model' },
];

export const QUANTIZATION_CATEGORIES = [
  {
    category: 'Full & Native Precision',
    options: [
      { label: 'None / Cloud Native', desc: 'Unquantized default provider cloud deployment' },
      { label: 'BF16 (Bfloat16)', desc: '16-bit Brain floating point standard' },
      { label: 'FP16 (Half Precision)', desc: 'Standard 16-bit floating point' },
      { label: 'FP32 (Single Precision)', desc: 'Full 32-bit floating point weights' },
    ],
  },
  {
    category: 'Modern FP8 & Low-Bit Float',
    options: [
      { label: 'FP8 (E4M3)', desc: '8-bit float optimized for inference (Hopper/Ada)' },
      { label: 'FP8 (E5M2)', desc: '8-bit float with wider dynamic range' },
      { label: 'NVFP4 (NVIDIA 4-bit)', desc: 'Next-gen Blackwell 4-bit floating point' },
    ],
  },
  {
    category: 'GGUF / llama.cpp (Local)',
    options: [
      { label: 'Q4_K_M (Recommended 4-bit)', desc: 'Optimal balance of speed, RAM and perplexity' },
      { label: 'Q4_K_S (Fast 4-bit)', desc: 'Slightly smaller 4-bit quantization' },
      { label: 'Q5_K_M (High Quality 5-bit)', desc: 'Near FP16 quality with 5-bit compression' },
      { label: 'Q6_K (6-bit)', desc: 'Highest fidelity local quantization' },
      { label: 'Q8_0 (8-bit Integer)', desc: 'Virtually lossless 8-bit integer quantization' },
      { label: 'Q3_K_M (Compact 3-bit)', desc: 'Aggressive compression for limited VRAM' },
      { label: 'Q2_K (Extreme 2-bit)', desc: 'Ultra-compressed experimental quantization' },
    ],
  },
  {
    category: 'AWQ, EXL2 & GPTQ',
    options: [
      { label: 'AWQ 4-bit', desc: 'Activation-aware weight quantization (vLLM / SGLang)' },
      { label: 'GPTQ 4-bit', desc: 'Second-order error compensation quantization' },
      { label: 'EXL2 4.0 bpw', desc: 'ExLlamaV2 high-throughput 4.0 bits-per-weight' },
      { label: 'EXL2 6.0 bpw', desc: 'ExLlamaV2 high-fidelity 6.0 bits-per-weight' },
      { label: 'HQQ 4-bit', desc: 'Half-Quadratic Quantization' },
    ],
  },
];

export const PARAMETER_SCALE_PILLS = [
  '1.5B',
  '3B',
  '7B',
  '8B',
  '14B',
  '27B',
  '32B',
  '70B',
  'MoE 8x7B',
  'MoE 8x22B',
  'MoE 671B (37B active)',
  '120B+',
  'Proprietary Cloud',
];

export const CONTEXT_WINDOW_PILLS = [
  '8k',
  '16k',
  '32k',
  '64k',
  '128k',
  '200k',
  '1M',
  '2M',
];

export const MODEL_TEMPLATES: ModelPresetTemplate[] = [
  // ==========================================
  // 🧠 REASONING & CHAIN-OF-THOUGHT LEADERS
  // ==========================================
  {
    id: 'claude-3-7-sonnet-thinking',
    name: '🧠 Claude 3.7 Sonnet (Hybrid Thinking)',
    provider: 'Anthropic',
    modelName: 'claude-3-7-sonnet-20250219',
    displayName: 'Claude 3.7 Sonnet (Thinking)',
    modelFamily: 'Claude 3.7',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: 'State-of-the-art hybrid reasoning model with dynamic thinking budget for complex frontend applications.',
    aaIntelligenceIndex: 91.8,
    aaModelId: 'claude-3-7-sonnet',
    aaEvaluations: {
      gpqa: 75.8,
      math: 96.2,
      coding: 94.0,
      throughputTokSec: 68.0,
      priceInputPer1M: 3.0,
      priceOutputPer1M: 15.0,
    },
  },
  {
    id: 'deepseek-r1',
    name: '🧠 DeepSeek R1 (671B MoE Reasoning)',
    provider: 'DeepSeek',
    modelName: 'deepseek-reasoner',
    displayName: 'DeepSeek R1',
    modelFamily: 'DeepSeek R1',
    parameterCount: 'MoE 671B (37B active)',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: 'Open-weights reinforcement-learning trained flagship reasoning model with complete chain-of-thought verification.',
    aaIntelligenceIndex: 88.6,
    aaModelId: 'deepseek-r1',
    aaEvaluations: {
      gpqa: 71.5,
      math: 97.3,
      coding: 89.2,
      throughputTokSec: 28.5,
      priceInputPer1M: 0.55,
      priceOutputPer1M: 2.19,
    },
  },
  {
    id: 'openai-o3-mini',
    name: '🧠 OpenAI o3-mini (High Speed Reasoning)',
    provider: 'OpenAI',
    modelName: 'o3-mini',
    displayName: 'OpenAI o3-mini',
    modelFamily: 'OpenAI o3',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: 'High-throughput STEM and algorithmic reasoning model with adjustable thinking effort.',
    aaIntelligenceIndex: 86.4,
    aaModelId: 'o3-mini',
    aaEvaluations: {
      gpqa: 79.7,
      math: 97.9,
      coding: 92.4,
      throughputTokSec: 95.0,
      priceInputPer1M: 1.1,
      priceOutputPer1M: 4.4,
    },
  },
  {
    id: 'openai-o1',
    name: '🧠 OpenAI o1 (Full Reasoning Flagship)',
    provider: 'OpenAI',
    modelName: 'o1',
    displayName: 'OpenAI o1',
    modelFamily: 'OpenAI o1',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: 'Full-scale reasoning model engineered for deep algorithmic, logic, and constraint synthesis.',
    aaIntelligenceIndex: 87.1,
    aaModelId: 'o1',
    aaEvaluations: {
      gpqa: 78.0,
      math: 96.4,
      coding: 91.0,
      throughputTokSec: 45.0,
      priceInputPer1M: 15.0,
      priceOutputPer1M: 60.0,
    },
  },
  {
    id: 'openai-o1-mini',
    name: '🧠 OpenAI o1-mini',
    provider: 'OpenAI',
    modelName: 'o1-mini',
    displayName: 'OpenAI o1-mini',
    modelFamily: 'OpenAI o1',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: 'Compact reasoning model specialized in math and coding.',
    aaIntelligenceIndex: 82.0,
    aaModelId: 'o1-mini',
    aaEvaluations: {
      gpqa: 60.0,
      math: 90.0,
      coding: 85.0,
      throughputTokSec: 85.0,
      priceInputPer1M: 1.1,
      priceOutputPer1M: 4.4,
    },
  },
  {
    id: 'gemini-2-0-flash-thinking',
    name: '🧠 Gemini 2.0 Flash Thinking Exp',
    provider: 'Google',
    modelName: 'gemini-2.0-flash-thinking-exp-01-21',
    displayName: 'Gemini 2.0 Flash Thinking',
    modelFamily: 'Gemini 2.0',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: 'Experimental multimodal reasoning model with transparent thinking process and 1M token context.',
    aaIntelligenceIndex: 84.5,
    aaModelId: 'gemini-2-0-flash-thinking-exp',
    aaEvaluations: {
      gpqa: 72.0,
      math: 92.0,
      coding: 88.0,
      throughputTokSec: 120.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.4,
    },
  },
  {
    id: 'qwq-32b-preview',
    name: '🧠 QwQ 32B Preview (Reasoning)',
    provider: 'Alibaba',
    modelName: 'qwq-32b-preview',
    displayName: 'QwQ 32B Preview',
    modelFamily: 'QwQ',
    parameterCount: '32B',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '32k',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: 'Alibaba open reasoning model delivering o1-level analytical performance in local inference.',
    aaIntelligenceIndex: 79.5,
    aaModelId: 'qwq-32b-preview',
    aaEvaluations: {
      gpqa: 65.2,
      math: 90.6,
      coding: 87.0,
      throughputTokSec: 38.0,
      priceInputPer1M: 0.3,
      priceOutputPer1M: 0.9,
    },
  },
  {
    id: 'deepseek-r1-distill-qwen-32b',
    name: '🧠 DeepSeek R1 Distill Qwen 32B',
    provider: 'DeepSeek',
    modelName: 'deepseek-r1-distill-qwen-32b',
    displayName: 'DeepSeek R1 Distill Qwen 32B',
    modelFamily: 'DeepSeek R1 Distill',
    parameterCount: '32B',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: 'Dense 32B distilled from DeepSeek-R1 reasoning trajectories on Qwen 2.5 base.',
    aaIntelligenceIndex: 78.8,
    aaModelId: 'deepseek-r1-distill-qwen-32b',
    aaEvaluations: {
      gpqa: 65.3,
      math: 91.5,
      coding: 86.8,
      throughputTokSec: 42.0,
      priceInputPer1M: 0.25,
      priceOutputPer1M: 0.75,
    },
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: '🧠 DeepSeek R1 Distill Llama 70B',
    provider: 'DeepSeek',
    modelName: 'deepseek-r1-distill-llama-70b',
    displayName: 'DeepSeek R1 Distill Llama 70B',
    modelFamily: 'DeepSeek R1 Distill',
    parameterCount: '70B',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: true,
    categoryTag: 'Reasoning',
    notes: '70B dense model distilled from DeepSeek-R1 fine-tuned on Llama 3.3 base.',
    aaIntelligenceIndex: 81.2,
    aaModelId: 'deepseek-r1-distill-llama-70b',
    aaEvaluations: {
      gpqa: 68.2,
      math: 93.0,
      coding: 88.5,
      throughputTokSec: 26.0,
      priceInputPer1M: 0.45,
      priceOutputPer1M: 1.35,
    },
  },

  // ==========================================
  // ⚡ ANTHROPIC CLAUDE 3.7 & 3.5 FAMILY
  // ==========================================
  {
    id: 'claude-3-7-sonnet-standard',
    name: '⚡ Claude 3.7 Sonnet (Standard)',
    provider: 'Anthropic',
    modelName: 'claude-3-7-sonnet-20250219',
    displayName: 'Claude 3.7 Sonnet (Standard)',
    modelFamily: 'Claude 3.7',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: false,
    categoryTag: 'Anthropic',
    notes: 'Next-generation standard generation mode with unmatched code formatting and HTML/JS precision.',
    aaIntelligenceIndex: 89.5,
    aaModelId: 'claude-3-7-sonnet-standard',
    aaEvaluations: {
      gpqa: 70.2,
      math: 88.0,
      coding: 93.5,
      throughputTokSec: 78.0,
      priceInputPer1M: 3.0,
      priceOutputPer1M: 15.0,
    },
  },
  {
    id: 'claude-3-5-sonnet-v2',
    name: '⚡ Claude 3.5 Sonnet v2 (20241022)',
    provider: 'Anthropic',
    modelName: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet v2',
    modelFamily: 'Claude 3.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: false,
    categoryTag: 'Anthropic',
    notes: 'Industry standard for frontend Canvas, 3D WebGL, and single-file application generation.',
    aaIntelligenceIndex: 82.3,
    aaModelId: 'claude-3-5-sonnet',
    aaEvaluations: {
      gpqa: 65.0,
      math: 78.3,
      coding: 92.0,
      throughputTokSec: 74.0,
      priceInputPer1M: 3.0,
      priceOutputPer1M: 15.0,
    },
  },
  {
    id: 'claude-3-5-haiku',
    name: '⚡ Claude 3.5 Haiku',
    provider: 'Anthropic',
    modelName: 'claude-3-5-haiku-20241022',
    displayName: 'Claude 3.5 Haiku',
    modelFamily: 'Claude 3.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: false,
    categoryTag: 'Anthropic',
    notes: 'Ultra-fast compact model with exceptional code generation speed.',
    aaIntelligenceIndex: 68.9,
    aaModelId: 'claude-3-5-haiku',
    aaEvaluations: {
      gpqa: 54.0,
      math: 69.2,
      coding: 78.5,
      throughputTokSec: 112.0,
      priceInputPer1M: 0.8,
      priceOutputPer1M: 4.0,
    },
  },
  {
    id: 'claude-3-opus',
    name: '⚡ Claude 3 Opus',
    provider: 'Anthropic',
    modelName: 'claude-3-opus-20240229',
    displayName: 'Claude 3 Opus',
    modelFamily: 'Claude 3',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '200k',
    isReasoningModel: false,
    categoryTag: 'Anthropic',
    notes: 'Anthropic premier complex synthesis and nuanced writing model.',
    aaIntelligenceIndex: 77.5,
    aaModelId: 'claude-3-opus',
    aaEvaluations: {
      gpqa: 50.4,
      math: 60.1,
      coding: 84.0,
      throughputTokSec: 32.0,
      priceInputPer1M: 15.0,
      priceOutputPer1M: 75.0,
    },
  },

  // ==========================================
  // 🌟 OPENAI GPT & OMNI FAMILY
  // ==========================================
  {
    id: 'gpt-4-5-preview',
    name: '🌟 OpenAI GPT-4.5 Preview',
    provider: 'OpenAI',
    modelName: 'gpt-4.5-preview-2025-02-27',
    displayName: 'OpenAI GPT-4.5 Preview',
    modelFamily: 'GPT-4.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'OpenAI',
    notes: 'Largest world-knowledge and creative alignment model by OpenAI with massive parameter scale.',
    aaIntelligenceIndex: 88.0,
    aaModelId: 'gpt-4-5-preview',
    aaEvaluations: {
      gpqa: 68.0,
      math: 85.0,
      coding: 91.0,
      throughputTokSec: 40.0,
      priceInputPer1M: 75.0,
      priceOutputPer1M: 150.0,
    },
  },
  {
    id: 'gpt-4o',
    name: '🌟 OpenAI GPT-4o (Omni)',
    provider: 'OpenAI',
    modelName: 'gpt-4o-2024-11-20',
    displayName: 'OpenAI GPT-4o',
    modelFamily: 'GPT-4o',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'OpenAI',
    notes: 'Flagship multimodal generative model for general code synthesis and visual HTML layouts.',
    aaIntelligenceIndex: 81.0,
    aaModelId: 'gpt-4o',
    aaEvaluations: {
      gpqa: 53.6,
      math: 76.6,
      coding: 88.0,
      throughputTokSec: 85.0,
      priceInputPer1M: 2.5,
      priceOutputPer1M: 10.0,
    },
  },
  {
    id: 'gpt-4o-mini',
    name: '🌟 OpenAI GPT-4o mini',
    provider: 'OpenAI',
    modelName: 'gpt-4o-mini',
    displayName: 'OpenAI GPT-4o mini',
    modelFamily: 'GPT-4o',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'OpenAI',
    notes: 'Cost-efficient lightweight model for fast UI component iterations.',
    aaIntelligenceIndex: 64.5,
    aaModelId: 'gpt-4o-mini',
    aaEvaluations: {
      gpqa: 40.2,
      math: 70.2,
      coding: 72.0,
      throughputTokSec: 130.0,
      priceInputPer1M: 0.15,
      priceOutputPer1M: 0.6,
    },
  },

  // ==========================================
  // ⚡ DEEPSEEK SERIES
  // ==========================================
  {
    id: 'deepseek-v3',
    name: '⚡ DeepSeek V3 (671B MoE MLA)',
    provider: 'DeepSeek',
    modelName: 'deepseek-chat',
    displayName: 'DeepSeek V3',
    modelFamily: 'DeepSeek V3',
    parameterCount: 'MoE 671B (37B active)',
    architecture: 'Transformer + Multi-Head Latent Attention (MLA)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'DeepSeek',
    notes: 'Ultra-fast sparse MoE architecture with Multi-Head Latent Attention (MLA).',
    aaIntelligenceIndex: 78.4,
    aaModelId: 'deepseek-v3',
    aaEvaluations: {
      gpqa: 59.1,
      math: 89.3,
      coding: 84.1,
      throughputTokSec: 62.0,
      priceInputPer1M: 0.27,
      priceOutputPer1M: 1.1,
    },
  },
  {
    id: 'deepseek-coder-v2-5',
    name: '⚡ DeepSeek Coder V2.5 (236B MoE)',
    provider: 'DeepSeek',
    modelName: 'deepseek-coder-v2.5',
    displayName: 'DeepSeek Coder V2.5',
    modelFamily: 'DeepSeek Coder',
    parameterCount: 'MoE 236B (21B active)',
    architecture: 'Mixture of Experts (MoE)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'DeepSeek',
    notes: 'Dedicated code generation and math model with extensive FIM capability.',
    aaIntelligenceIndex: 74.8,
    aaModelId: 'deepseek-coder-v2-5',
    aaEvaluations: {
      gpqa: 49.0,
      math: 80.0,
      coding: 88.0,
      throughputTokSec: 52.0,
      priceInputPer1M: 0.14,
      priceOutputPer1M: 0.28,
    },
  },

  // ==========================================
  // 🔮 GOOGLE GEMINI 2.0 & 1.5 FAMILY
  // ==========================================
  {
    id: 'gemini-2-0-flash',
    name: '🔮 Google Gemini 2.0 Flash',
    provider: 'Google',
    modelName: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash',
    modelFamily: 'Gemini 2.0',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: false,
    categoryTag: 'Google',
    notes: 'Flagship ultra-high-speed multimodal generation with 1M native context window.',
    aaIntelligenceIndex: 78.9,
    aaModelId: 'gemini-2-0-flash',
    aaEvaluations: {
      gpqa: 62.1,
      math: 84.0,
      coding: 82.5,
      throughputTokSec: 150.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.4,
    },
  },
  {
    id: 'gemini-2-0-pro-exp',
    name: '🔮 Google Gemini 2.0 Pro Exp',
    provider: 'Google',
    modelName: 'gemini-2.0-pro-exp-02-05',
    displayName: 'Gemini 2.0 Pro Exp',
    modelFamily: 'Gemini 2.0',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '2M',
    isReasoningModel: false,
    categoryTag: 'Google',
    notes: 'Google most capable coding and complex reasoning model with 2M context.',
    aaIntelligenceIndex: 85.0,
    aaModelId: 'gemini-2-0-pro-exp',
    aaEvaluations: {
      gpqa: 71.0,
      math: 89.0,
      coding: 89.5,
      throughputTokSec: 65.0,
      priceInputPer1M: 1.25,
      priceOutputPer1M: 5.0,
    },
  },
  {
    id: 'gemini-1-5-pro',
    name: '🔮 Google Gemini 1.5 Pro (002)',
    provider: 'Google',
    modelName: 'gemini-1.5-pro-002',
    displayName: 'Gemini 1.5 Pro (002)',
    modelFamily: 'Gemini 1.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '2M',
    isReasoningModel: false,
    categoryTag: 'Google',
    notes: '2M token long-context production foundation model.',
    aaIntelligenceIndex: 77.8,
    aaModelId: 'gemini-1-5-pro-002',
    aaEvaluations: {
      gpqa: 55.9,
      math: 82.0,
      coding: 84.0,
      throughputTokSec: 60.0,
      priceInputPer1M: 1.25,
      priceOutputPer1M: 5.0,
    },
  },

  // ==========================================
  // 🦙 META LLAMA 3.3 / 3.2 / 3.1 FAMILY
  // ==========================================
  {
    id: 'llama-3-3-70b',
    name: '🦙 Meta Llama 3.3 70B Instruct',
    provider: 'Meta',
    modelName: 'llama3.3:70b',
    displayName: 'Llama 3.3 70B',
    modelFamily: 'Llama 3.3',
    parameterCount: '70B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Meta',
    notes: 'Flagship open dense model matching 405B capabilities at 70B parameter scale.',
    aaIntelligenceIndex: 76.5,
    aaModelId: 'llama-3-3-70b-instruct',
    aaEvaluations: {
      gpqa: 54.0,
      math: 81.0,
      coding: 83.2,
      throughputTokSec: 32.0,
      priceInputPer1M: 0.35,
      priceOutputPer1M: 1.0,
    },
  },
  {
    id: 'llama-3-1-405b',
    name: '🦙 Meta Llama 3.1 405B Instruct',
    provider: 'Meta',
    modelName: 'llama3.1:405b',
    displayName: 'Llama 3.1 405B',
    modelFamily: 'Llama 3.1',
    parameterCount: '120B+',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'FP8 (E4M3)',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Meta',
    notes: 'Largest open weights frontier model by Meta AI.',
    aaIntelligenceIndex: 79.2,
    aaModelId: 'llama-3-1-405b-instruct',
    aaEvaluations: {
      gpqa: 58.0,
      math: 82.5,
      coding: 85.0,
      throughputTokSec: 20.0,
      priceInputPer1M: 1.5,
      priceOutputPer1M: 3.5,
    },
  },
  {
    id: 'llama-3-1-70b',
    name: '🦙 Meta Llama 3.1 70B Instruct',
    provider: 'Meta',
    modelName: 'llama3.1:70b',
    displayName: 'Llama 3.1 70B',
    modelFamily: 'Llama 3.1',
    parameterCount: '70B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Meta',
    notes: 'Dense 70B model with 128k context.',
    aaIntelligenceIndex: 74.0,
    aaModelId: 'llama-3-1-70b-instruct',
    aaEvaluations: {
      gpqa: 48.0,
      math: 76.0,
      coding: 80.0,
      throughputTokSec: 34.0,
      priceInputPer1M: 0.35,
      priceOutputPer1M: 0.9,
    },
  },
  {
    id: 'llama-3-1-8b',
    name: '🦙 Meta Llama 3.1 8B Instruct',
    provider: 'Meta',
    modelName: 'llama3.1:8b',
    displayName: 'Llama 3.1 8B',
    modelFamily: 'Llama 3.1',
    parameterCount: '8B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Meta',
    notes: 'Fast lightweight model for consumer hardware inference.',
    aaIntelligenceIndex: 56.2,
    aaModelId: 'llama-3-1-8b-instruct',
    aaEvaluations: {
      gpqa: 32.8,
      math: 52.0,
      coding: 65.0,
      throughputTokSec: 95.0,
      priceInputPer1M: 0.05,
      priceOutputPer1M: 0.15,
    },
  },
  {
    id: 'llama-3-2-3b',
    name: '🦙 Meta Llama 3.2 3B Instruct',
    provider: 'Meta',
    modelName: 'llama3.2:3b',
    displayName: 'Llama 3.2 3B',
    modelFamily: 'Llama 3.2',
    parameterCount: '3B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Meta',
    notes: 'Ultra-lightweight on-device model capable of 128k context.',
    aaIntelligenceIndex: 48.0,
    aaModelId: 'llama-3-2-3b-instruct',
    aaEvaluations: {
      gpqa: 25.0,
      math: 42.0,
      coding: 54.0,
      throughputTokSec: 140.0,
      priceInputPer1M: 0.02,
      priceOutputPer1M: 0.06,
    },
  },

  // ==========================================
  // 💻 ALIBABA QWEN 2.5 FAMILY
  // ==========================================
  {
    id: 'qwen-2-5-coder-32b',
    name: '💻 Qwen 2.5 Coder 32B Instruct',
    provider: 'Alibaba',
    modelName: 'qwen2.5-coder:32b',
    displayName: 'Qwen 2.5 Coder 32B',
    modelFamily: 'Qwen 2.5',
    parameterCount: '32B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Alibaba',
    notes: 'Top-tier open code model matching GPT-4o level code generation in local inference.',
    aaIntelligenceIndex: 74.2,
    aaModelId: 'qwen-2-5-coder-32b-instruct',
    aaEvaluations: {
      gpqa: 48.0,
      math: 82.0,
      coding: 86.5,
      throughputTokSec: 42.0,
      priceInputPer1M: 0.2,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'qwen-2-5-coder-14b',
    name: '💻 Qwen 2.5 Coder 14B Instruct',
    provider: 'Alibaba',
    modelName: 'qwen2.5-coder:14b',
    displayName: 'Qwen 2.5 Coder 14B',
    modelFamily: 'Qwen 2.5',
    parameterCount: '14B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Alibaba',
    notes: 'High-density code model fitting comfortably in 12GB VRAM.',
    aaIntelligenceIndex: 68.0,
    aaModelId: 'qwen-2-5-coder-14b-instruct',
    aaEvaluations: {
      gpqa: 42.0,
      math: 75.0,
      coding: 81.0,
      throughputTokSec: 68.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.3,
    },
  },
  {
    id: 'qwen-2-5-coder-7b',
    name: '💻 Qwen 2.5 Coder 7B Instruct',
    provider: 'Alibaba',
    modelName: 'qwen2.5-coder:7b',
    displayName: 'Qwen 2.5 Coder 7B',
    modelFamily: 'Qwen 2.5',
    parameterCount: '7B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Alibaba',
    notes: 'Ultra-fast 7B code model ideal for continuous benchmarking iterations.',
    aaIntelligenceIndex: 62.0,
    aaModelId: 'qwen-2-5-coder-7b-instruct',
    aaEvaluations: {
      gpqa: 36.0,
      math: 68.0,
      coding: 76.0,
      throughputTokSec: 110.0,
      priceInputPer1M: 0.05,
      priceOutputPer1M: 0.15,
    },
  },
  {
    id: 'qwen-2-5-72b',
    name: '💻 Qwen 2.5 72B Instruct',
    provider: 'Alibaba',
    modelName: 'qwen2.5:72b',
    displayName: 'Qwen 2.5 72B',
    modelFamily: 'Qwen 2.5',
    parameterCount: '70B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Alibaba',
    notes: 'Large open-weights flagship model with strong general coding and multilingual mastery.',
    aaIntelligenceIndex: 77.0,
    aaModelId: 'qwen-2-5-72b-instruct',
    aaEvaluations: {
      gpqa: 55.4,
      math: 85.2,
      coding: 85.0,
      throughputTokSec: 25.0,
      priceInputPer1M: 0.4,
      priceOutputPer1M: 1.2,
    },
  },
  {
    id: 'qwen-2-5-max',
    name: '💻 Qwen 2.5 Max (Hosted Flagship)',
    provider: 'Alibaba',
    modelName: 'qwen-2.5-max',
    displayName: 'Qwen 2.5 Max',
    modelFamily: 'Qwen 2.5',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Mixture of Experts (MoE)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '32k',
    isReasoningModel: false,
    categoryTag: 'Alibaba',
    notes: 'Alibaba largest hosted MoE model outperforming dense 72B in complex logic.',
    aaIntelligenceIndex: 82.5,
    aaModelId: 'qwen-2-5-max',
    aaEvaluations: {
      gpqa: 64.0,
      math: 88.0,
      coding: 89.0,
      throughputTokSec: 50.0,
      priceInputPer1M: 1.6,
      priceOutputPer1M: 4.8,
    },
  },

  // ==========================================
  // ⚡ XAI GROK FAMILY
  // ==========================================
  {
    id: 'grok-3',
    name: '⚡ xAI Grok 3',
    provider: 'xAI',
    modelName: 'grok-3',
    displayName: 'xAI Grok 3',
    modelFamily: 'Grok 3',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Reasoning / Thinking Model',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '1M',
    isReasoningModel: true,
    categoryTag: 'xAI',
    notes: 'xAI frontier flagship reasoning and generation model trained on massive Colossus cluster.',
    aaIntelligenceIndex: 90.5,
    aaModelId: 'grok-3',
    aaEvaluations: {
      gpqa: 75.0,
      math: 95.0,
      coding: 93.0,
      throughputTokSec: 60.0,
      priceInputPer1M: 3.0,
      priceOutputPer1M: 15.0,
    },
  },
  {
    id: 'grok-2',
    name: '⚡ xAI Grok 2 (1212)',
    provider: 'xAI',
    modelName: 'grok-2-1212',
    displayName: 'xAI Grok 2',
    modelFamily: 'Grok 2',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'xAI',
    notes: 'State-of-the-art vision and language model by xAI.',
    aaIntelligenceIndex: 79.5,
    aaModelId: 'grok-2',
    aaEvaluations: {
      gpqa: 56.0,
      math: 78.0,
      coding: 86.0,
      throughputTokSec: 70.0,
      priceInputPer1M: 2.0,
      priceOutputPer1M: 10.0,
    },
  },

  // ==========================================
  // 🌪️ MISTRAL AI FAMILY
  // ==========================================
  {
    id: 'mistral-large-2411',
    name: '🌪️ Mistral Large 2 (2411)',
    provider: 'Mistral AI',
    modelName: 'mistral-large-2411',
    displayName: 'Mistral Large 2',
    modelFamily: 'Mistral Large',
    parameterCount: '120B+',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Mistral',
    notes: 'Flagship multilingual coding model by Mistral AI with 123B parameters.',
    aaIntelligenceIndex: 78.2,
    aaModelId: 'mistral-large-2411',
    aaEvaluations: {
      gpqa: 55.0,
      math: 76.5,
      coding: 84.5,
      throughputTokSec: 58.0,
      priceInputPer1M: 2.0,
      priceOutputPer1M: 6.0,
    },
  },
  {
    id: 'codestral-2501',
    name: '🌪️ Mistral Codestral 2501',
    provider: 'Mistral AI',
    modelName: 'codestral-latest',
    displayName: 'Codestral 25.01',
    modelFamily: 'Codestral',
    parameterCount: '27B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '256k',
    isReasoningModel: false,
    categoryTag: 'Mistral',
    notes: 'Specialized code generation and FIM (Fill-in-the-Middle) model with 256k context.',
    aaIntelligenceIndex: 72.5,
    aaModelId: 'codestral-2501',
    aaEvaluations: {
      gpqa: 46.2,
      math: 70.0,
      coding: 87.5,
      throughputTokSec: 90.0,
      priceInputPer1M: 0.3,
      priceOutputPer1M: 0.9,
    },
  },
  {
    id: 'mistral-small-24b-2501',
    name: '🌪️ Mistral Small 3 (24B)',
    provider: 'Mistral AI',
    modelName: 'mistral-small-24b-instruct-2501',
    displayName: 'Mistral Small 3 (24B)',
    modelFamily: 'Mistral Small',
    parameterCount: '27B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '32k',
    isReasoningModel: false,
    categoryTag: 'Mistral',
    notes: 'Compact 24B Apache 2.0 open model matching Llama 3.3 70B in concise code generation.',
    aaIntelligenceIndex: 73.0,
    aaModelId: 'mistral-small-24b-instruct-2501',
    aaEvaluations: {
      gpqa: 48.0,
      math: 72.0,
      coding: 82.0,
      throughputTokSec: 65.0,
      priceInputPer1M: 0.2,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'ministral-8b',
    name: '🌪️ Ministral 8B (2410)',
    provider: 'Mistral AI',
    modelName: 'ministral-8b-2410',
    displayName: 'Ministral 8B',
    modelFamily: 'Ministral',
    parameterCount: '8B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Mistral',
    notes: 'High-density edge model designed for low-latency code execution and function calling.',
    aaIntelligenceIndex: 61.5,
    aaModelId: 'ministral-8b',
    aaEvaluations: {
      gpqa: 38.0,
      math: 60.0,
      coding: 73.0,
      throughputTokSec: 105.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.1,
    },
  },

  // ==========================================
  // 🔬 MICROSOFT PHI & OTHER CHAMPIONS
  // ==========================================
  {
    id: 'phi-4-14b',
    name: '🔬 Microsoft Phi-4 (14B)',
    provider: 'Microsoft',
    modelName: 'phi4:14b',
    displayName: 'Microsoft Phi-4 (14B)',
    modelFamily: 'Phi-4',
    parameterCount: '14B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '16k',
    isReasoningModel: false,
    categoryTag: 'Microsoft',
    notes: 'Synthetic-data trained reasoning and code model with exceptional benchmark density.',
    aaIntelligenceIndex: 71.5,
    aaModelId: 'phi-4',
    aaEvaluations: {
      gpqa: 51.0,
      math: 80.4,
      coding: 80.0,
      throughputTokSec: 65.0,
      priceInputPer1M: 0.1,
      priceOutputPer1M: 0.3,
    },
  },
  {
    id: 'phi-4-mini',
    name: '🔬 Microsoft Phi-4 Mini (3.8B)',
    provider: 'Microsoft',
    modelName: 'phi4-mini',
    displayName: 'Microsoft Phi-4 Mini',
    modelFamily: 'Phi-4',
    parameterCount: '3B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Microsoft',
    notes: 'Ultra-compact 3.8B model with 128k context and high math capability.',
    aaIntelligenceIndex: 58.0,
    aaModelId: 'phi-4-mini',
    aaEvaluations: {
      gpqa: 35.0,
      math: 68.0,
      coding: 68.0,
      throughputTokSec: 135.0,
      priceInputPer1M: 0.03,
      priceOutputPer1M: 0.09,
    },
  },
  {
    id: 'gemma-2-27b',
    name: '💎 Google Gemma 2 27B Instruct',
    provider: 'Google',
    modelName: 'gemma2:27b',
    displayName: 'Gemma 2 27B',
    modelFamily: 'Gemma 2',
    parameterCount: '27B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '8k',
    isReasoningModel: false,
    categoryTag: 'Google',
    notes: 'Google open weights model trained with knowledge distillation.',
    aaIntelligenceIndex: 69.5,
    aaModelId: 'gemma-2-27b-it',
    aaEvaluations: {
      gpqa: 44.0,
      math: 68.0,
      coding: 75.0,
      throughputTokSec: 48.0,
      priceInputPer1M: 0.2,
      priceOutputPer1M: 0.6,
    },
  },
  {
    id: 'command-r-plus-08-2024',
    name: '🌐 Cohere Command R+ (08-2024)',
    provider: 'Cohere',
    modelName: 'command-r-plus-08-2024',
    displayName: 'Command R+ (08-2024)',
    modelFamily: 'Command R+',
    parameterCount: '120B+',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '128k',
    isReasoningModel: false,
    categoryTag: 'Cohere',
    notes: 'Enterprise foundation model with tool use and multilingual capabilities.',
    aaIntelligenceIndex: 72.0,
    aaModelId: 'command-r-plus-08-2024',
    aaEvaluations: {
      gpqa: 42.5,
      math: 65.0,
      coding: 78.0,
      throughputTokSec: 55.0,
      priceInputPer1M: 2.5,
      priceOutputPer1M: 10.0,
    },
  },
  {
    id: 'amazon-nova-pro',
    name: '📦 Amazon Nova Pro',
    provider: 'Amazon Bedrock',
    modelName: 'amazon.nova-pro-v1:0',
    displayName: 'Amazon Nova Pro',
    modelFamily: 'Amazon Nova',
    parameterCount: 'Proprietary Cloud',
    architecture: 'Vision-Language Multimodal (VLM)',
    quantization: 'None / Cloud Native',
    localOrCloud: 'cloud',
    contextWindow: '300k',
    isReasoningModel: false,
    categoryTag: 'Amazon',
    notes: 'Amazon frontier multimodal model engineered for complex reasoning and application logic.',
    aaIntelligenceIndex: 78.0,
    aaModelId: 'amazon-nova-pro',
    aaEvaluations: {
      gpqa: 54.0,
      math: 76.0,
      coding: 83.0,
      throughputTokSec: 75.0,
      priceInputPer1M: 0.8,
      priceOutputPer1M: 3.2,
    },
  },
  {
    id: 'smollm2-1-7b',
    name: '🤗 SmolLM2 1.7B Instruct',
    provider: 'Hugging Face',
    modelName: 'smollm2:1.7b',
    displayName: 'SmolLM2 1.7B',
    modelFamily: 'SmolLM2',
    parameterCount: '1.5B',
    architecture: 'Transformer (Decoder-only Dense)',
    quantization: 'Q4_K_M (Recommended 4-bit)',
    localOrCloud: 'local',
    contextWindow: '8k',
    isReasoningModel: false,
    categoryTag: 'HuggingFace',
    notes: 'High performance small language model by Hugging Face running in under 2GB RAM.',
    aaIntelligenceIndex: 42.0,
    aaModelId: 'smollm2-1-7b',
    aaEvaluations: {
      gpqa: 20.0,
      math: 35.0,
      coding: 48.0,
      throughputTokSec: 180.0,
      priceInputPer1M: 0.01,
      priceOutputPer1M: 0.03,
    },
  },
];
