import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import { BenchmarkStats, ModelRanking, CategoryStat, ModelRun } from '@shared/types/entities';
import { ScoreBadge } from '../components/common/ScoreBadge';
import { Button } from '../components/common/Button';
import {
  Layers,
  Cpu,
  PlaySquare,
  Trophy,
  Award,
  Plus,
  TrendingUp,
  Sparkles,
} from 'lucide-react';

export const DashboardPage: React.FC = () => {
  const {
    setCurrentTab,
    setSelectedPromptId,
    setIsNewPromptModalOpen,
    setIsNewModelModalOpen,
    openCompareWithRuns,
    models,
  } = useApp();

  const [stats, setStats] = useState<BenchmarkStats | null>(null);
  const [loading, setLoading] = useState<boolean>(true);

  const fetchStats = async () => {
    try {
      if (window.electronAPI) {
        const res = await window.electronAPI.getBenchmarkStats();
        setStats(res);
      }
    } catch (err) {
      console.error('Failed to load benchmark stats:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStats();
  }, [models]);

  if (loading) {
    return (
      <div style={{ padding: '24px', color: 'var(--text-muted)' }}>
        Loading benchmark intelligence...
      </div>
    );
  }

  const isEmpty = !stats || stats.total_prompts === 0;

  return (
    <div
      style={{
        flex: 1,
        overflowY: 'auto',
        padding: '20px 24px',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
      }}
    >
      {/* Header Banner */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
        <div>
          <h1 className="h1">LLM HTML Benchmark Laboratory</h1>
          <p style={{ fontSize: '12px', color: 'var(--text-secondary)', marginTop: '2px' }}>
            Systematic repository for long-term evaluation and side-by-side inspection of frontend generation models.
          </p>
        </div>

        <div style={{ display: 'flex', gap: '8px' }}>
          <Button variant="primary" size="sm" icon={<Plus size={14} />} onClick={() => setIsNewPromptModalOpen(true)}>
            New Prompt
          </Button>
          <Button variant="secondary" size="sm" icon={<Cpu size={14} />} onClick={() => setIsNewModelModalOpen(true)}>
            Register Model
          </Button>
        </div>
      </div>

      {isEmpty ? (
        /* First Run Welcome Card */
        <div
          style={{
            padding: '36px',
            backgroundColor: 'var(--bg-secondary)',
            borderRadius: 'var(--radius-lg)',
            border: '1px dashed var(--border-color)',
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: '14px',
            marginTop: '20px',
          }}
        >
          <div
            style={{
              width: '48px',
              height: '48px',
              borderRadius: '50%',
              backgroundColor: 'var(--accent-primary-light)',
              color: 'var(--accent-primary)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Sparkles size={24} />
          </div>
          <div>
            <h2 className="h2" style={{ marginBottom: '6px' }}>Welcome to LLM HTML Bench</h2>
            <p style={{ fontSize: '13px', color: 'var(--text-secondary)', maxWidth: '540px' }}>
              Create your first benchmark prompt, then submit or paste outputs generated by different LLMs (e.g. Qwen, GPT-5, Claude, Gemini, or local models) to inspect and compare them side-by-side.
            </p>
          </div>
          <Button variant="primary" size="lg" icon={<Plus size={16} />} onClick={() => setIsNewPromptModalOpen(true)}>
            Create First Prompt
          </Button>
        </div>
      ) : (
        <>
          {/* Top Metric Cards */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
              gap: '12px',
            }}
          >
            <div
              style={{
                backgroundColor: 'var(--bg-card)',
                padding: '14px 16px',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-color)',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: 'var(--text-muted)' }}>
                <span style={{ fontSize: '11px', fontWeight: 600, textTransform: 'uppercase' }}>Prompts</span>
                <Layers size={15} color="var(--accent-primary)" />
              </div>
              <div style={{ fontSize: '24px', fontWeight: 700, marginTop: '6px', color: 'var(--text-primary)' }}>
                {stats.total_prompts}
              </div>
            </div>

            <div
              style={{
                backgroundColor: 'var(--bg-card)',
                padding: '14px 16px',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-color)',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: 'var(--text-muted)' }}>
                <span style={{ fontSize: '11px', fontWeight: 600, textTransform: 'uppercase' }}>Models</span>
                <Cpu size={15} color="var(--accent-purple)" />
              </div>
              <div style={{ fontSize: '24px', fontWeight: 700, marginTop: '6px', color: 'var(--text-primary)' }}>
                {stats.total_models}
              </div>
            </div>

            <div
              style={{
                backgroundColor: 'var(--bg-card)',
                padding: '14px 16px',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-color)',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: 'var(--text-muted)' }}>
                <span style={{ fontSize: '11px', fontWeight: 600, textTransform: 'uppercase' }}>Model Runs</span>
                <PlaySquare size={15} color="var(--accent-success)" />
              </div>
              <div style={{ fontSize: '24px', fontWeight: 700, marginTop: '6px', color: 'var(--text-primary)' }}>
                {stats.total_runs}
              </div>
            </div>

            <div
              style={{
                backgroundColor: 'var(--bg-card)',
                padding: '14px 16px',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-color)',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: 'var(--text-muted)' }}>
                <span style={{ fontSize: '11px', fontWeight: 600, textTransform: 'uppercase' }}>Evaluations</span>
                <Award size={15} color="var(--accent-warning)" />
              </div>
              <div style={{ fontSize: '24px', fontWeight: 700, marginTop: '6px', color: 'var(--text-primary)' }}>
                {stats.total_evaluations}
              </div>
            </div>

            <div
              style={{
                backgroundColor: 'var(--bg-card)',
                padding: '14px 16px',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-color)',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: 'var(--text-muted)' }}>
                <span style={{ fontSize: '11px', fontWeight: 600, textTransform: 'uppercase' }}>Head-to-Head</span>
                <Trophy size={15} color="var(--accent-cyan)" />
              </div>
              <div style={{ fontSize: '24px', fontWeight: 700, marginTop: '6px', color: 'var(--text-primary)' }}>
                {stats.total_comparisons}
              </div>
            </div>
          </div>

          {/* Model Leaderboard */}
          <div
            style={{
              backgroundColor: 'var(--bg-secondary)',
              borderRadius: 'var(--radius-md)',
              border: '1px solid var(--border-color)',
              overflow: 'hidden',
            }}
          >
            <div
              style={{
                padding: '12px 16px',
                borderBottom: '1px solid var(--border-color)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <TrendingUp size={16} color="var(--accent-primary)" />
                <h2 className="h2">Model Performance Leaderboard</h2>
              </div>
              <Button size="sm" variant="ghost" onClick={() => setCurrentTab('models')}>
                View All Models →
              </Button>
            </div>

            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px', textAlign: 'left' }}>
                <thead>
                  <tr style={{ backgroundColor: 'var(--bg-tertiary)', color: 'var(--text-secondary)', borderBottom: '1px solid var(--border-color)' }}>
                    <th style={{ padding: '8px 14px', width: '50px' }}>Rank</th>
                    <th style={{ padding: '8px 14px' }}>Model</th>
                    <th style={{ padding: '8px 14px' }}>Provider</th>
                    <th style={{ padding: '8px 14px' }}>Sample (n)</th>
                    <th style={{ padding: '8px 14px' }}>Overall Score</th>
                    <th style={{ padding: '8px 14px' }}>Visual</th>
                    <th style={{ padding: '8px 14px' }}>Adherence</th>
                    <th style={{ padding: '8px 14px' }}>Functionality</th>
                    <th style={{ padding: '8px 14px' }}>Code Quality</th>
                    <th style={{ padding: '8px 14px' }}>H2H Win Rate</th>
                  </tr>
                </thead>
                <tbody>
                  {stats.model_rankings.length === 0 ? (
                    <tr>
                      <td colSpan={10} style={{ padding: '16px', textAlign: 'center', color: 'var(--text-muted)' }}>
                        No model benchmarks evaluated yet.
                      </td>
                    </tr>
                  ) : (
                    stats.model_rankings.map((m: ModelRanking, idx: number) => (
                      <tr
                        key={m.model_id}
                        style={{
                          borderBottom: '1px solid var(--border-subtle)',
                          transition: 'background-color 0.1s ease',
                        }}
                      >
                        <td style={{ padding: '10px 14px', fontWeight: 600, color: idx === 0 ? 'var(--accent-warning)' : 'var(--text-muted)' }}>
                          #{idx + 1}
                        </td>
                        <td style={{ padding: '10px 14px', fontWeight: 600, color: 'var(--text-primary)' }}>
                          {m.display_name}
                        </td>
                        <td style={{ padding: '10px 14px', color: 'var(--text-secondary)' }}>
                          {m.provider}
                        </td>
                        <td style={{ padding: '10px 14px', fontFamily: 'var(--font-mono)', color: 'var(--text-muted)' }}>
                          n={m.run_count} ({m.prompt_count} prompts)
                        </td>
                        <td style={{ padding: '10px 14px' }}>
                          <ScoreBadge score={m.avg_overall} size="md" />
                        </td>
                        <td style={{ padding: '10px 14px', fontFamily: 'var(--font-mono)' }}>
                          {m.avg_visual > 0 ? m.avg_visual.toFixed(1) : '—'}
                        </td>
                        <td style={{ padding: '10px 14px', fontFamily: 'var(--font-mono)' }}>
                          {m.avg_adherence > 0 ? m.avg_adherence.toFixed(1) : '—'}
                        </td>
                        <td style={{ padding: '10px 14px', fontFamily: 'var(--font-mono)' }}>
                          {m.avg_functionality > 0 ? m.avg_functionality.toFixed(1) : '—'}
                        </td>
                        <td style={{ padding: '10px 14px', fontFamily: 'var(--font-mono)' }}>
                          {m.avg_code_quality > 0 ? m.avg_code_quality.toFixed(1) : '—'}
                        </td>
                        <td style={{ padding: '10px 14px' }}>
                          <span className="badge badge-primary">{m.win_rate}% ({m.head_to_head_wins}W - {m.head_to_head_losses}L)</span>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Bottom Grid: Categories & Recent Runs */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '14px' }}>
            {/* Category Breakdown */}
            <div
              style={{
                backgroundColor: 'var(--bg-secondary)',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-color)',
                padding: '14px',
              }}
            >
              <h3 className="h3" style={{ marginBottom: '12px' }}>Category Breakdown</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {stats.category_stats.map((c: CategoryStat) => (
                  <div
                    key={c.category}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      padding: '6px 10px',
                      backgroundColor: 'var(--bg-card)',
                      borderRadius: 'var(--radius-sm)',
                      border: '1px solid var(--border-subtle)',
                      fontSize: '12px',
                    }}
                  >
                    <span style={{ fontWeight: 500 }}>{c.category}</span>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <span style={{ color: 'var(--text-muted)', fontSize: '11px' }}>{c.prompt_count} prompts ({c.run_count} runs)</span>
                      {c.avg_score > 0 && <ScoreBadge score={c.avg_score} size="sm" />}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Recent Benchmark Runs */}
            <div
              style={{
                backgroundColor: 'var(--bg-secondary)',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-color)',
                padding: '14px',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
                <h3 className="h3">Recent Benchmark Runs</h3>
                <Button size="sm" variant="ghost" onClick={() => setCurrentTab('runs')}>
                  All Runs →
                </Button>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                {stats.recent_runs.length === 0 ? (
                  <div style={{ color: 'var(--text-muted)', fontSize: '12px', padding: '8px' }}>
                    No runs recorded yet.
                  </div>
                ) : (
                  stats.recent_runs.slice(0, 5).map((r: ModelRun) => (
                    <div
                      key={r.id}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        padding: '8px 10px',
                        backgroundColor: 'var(--bg-card)',
                        borderRadius: 'var(--radius-sm)',
                        border: '1px solid var(--border-subtle)',
                        fontSize: '12px',
                      }}
                    >
                      <div>
                        <div style={{ fontWeight: 600, color: 'var(--text-primary)' }}>
                          {r.prompt_name} <span style={{ fontWeight: 400, color: 'var(--text-muted)', fontSize: '11px' }}>(v{r.prompt_version})</span>
                        </div>
                        <div style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '1px' }}>
                          {r.model_display_name || r.model_name} • {new Date(r.started_at).toLocaleString()}
                        </div>
                      </div>

                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <ScoreBadge score={r.evaluation?.overall_score} size="md" />
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            if (r.prompt_id) {
                              setSelectedPromptId(r.prompt_id);
                              setCurrentTab('prompts');
                            }
                          }}
                        >
                          View
                        </Button>
                        <Button
                          size="sm"
                          variant="primary"
                          onClick={() => openCompareWithRuns([r.id])}
                        >
                          Compare
                        </Button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
